In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
old_matches = pd.read_csv('matches.csv')
old_matches

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
809,11469,2020,Dubai,01-11-2020,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,field,normal,0,Kolkata Knight Riders,60,6,Pat Cummins,Dubai International Cricket Stadium,Richard Illingworth,Chettithody Shamshuddin,KN Anantha Padmanabhan
810,11470,2020,Abu Dhabi,02-11-2020,Delhi Capitals,Royal Challengers Bangalore,Delhi Capitals,field,normal,0,Delhi Capitals,0,6,A Nortje,Sheikh Zayed Stadium,Chris Gaffaney,Sundaram Ravi,Virender Kumar Sharma
811,11471,2020,Sharjah,03-11-2020,Sunrisers Hyderabad,Mumbai Indians,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,10,S Nadeem,Sharjah Cricket Stadium,Richard Illingworth,Chettithody Shamshuddin,KN Anantha Padmanabhan
812,11472,2020,Dubai,05-10-2020,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,normal,0,Mumbai Indians,57,0,JJ Bumrah,Dubai International Cricket Stadium,Nitin Menon,Chris Gaffaney,KN Anantha Padmanabhan
813,11473,2020,Abu Dhabi,06-10-2020,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,6,Kane Williamson,Sheikh Zayed Stadium,Sundaram Ravi,Paul Reiffel,Virender Kumar Sharma

In [3]:
#sns.heatmap(old_matches.corr())

In [4]:
to_predict=pd.read_csv('2020 Schedule.csv')
#to_predict

In [5]:
old_matches['team2'].value_counts()

Royal Challengers Bangalore    103
Kolkata Knight Riders          102
Mumbai Indians                  93
Kings XI Punjab                 91
Delhi Daredevils                89
Rajasthan Royals                88
Chennai Super Kings             82
Sunrisers Hyderabad             52
Deccan Chargers                 32
Pune Warriors                   26
Delhi Capitals                  18
Gujarat Lions                   16
Rising Pune Supergiant           8
Kochi Tuskers Kerala             7
Rising Pune Supergiants          7
Name: team2, dtype: int64

In [6]:
sample=old_matches.drop(['id','season','city','date','result','dl_applied','win_by_runs','win_by_wickets','player_of_match','venue','umpire1','umpire2','umpire3'],axis=1)
sample

,team1,team2,toss_winner,toss_decision,winner
0,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad
1,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant
2,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders
3,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab
4,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore
...,...,...,...,...,...
809,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,field,Kolkata Knight Riders
810,Delhi Capitals,Royal Challengers Bangalore,Delhi Capitals,field,Delhi Capitals
811,Sunrisers Hyderabad,Mumbai Indians,Sunrisers Hyderabad,field,Sunrisers Hyderabad
812,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians
813,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,field,Sunrisers Hyderabad

In [7]:
#sns.heatmap(sample.corr())

In [8]:
x=['Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
    'Rising Pune Supergiant', 'Royal Challengers Bangalore',
    'Kolkata Knight Riders', 'Delhi Daredevils', 'Kings XI Punjab',
    'Chennai Super Kings', 'Rajasthan Royals', 'Deccan Chargers',
    'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants', 'Delhi Capitals']
#y = [1,2,3,4,5,6,7,8,9,10,11,12,13,4,14]
y = ['SRH','MI','GL','RPS','RCB','KKR','DC','KXIP','CSK','RR','SRH1','KTK','PW','RPS','DC']

sample.replace(x,y,inplace = True)
sample

    team1 team2 toss_winner toss_decision winner
0     SRH   RCB         RCB         field    SRH
1      MI   RPS         RPS         field    RPS
2      GL   KKR         KKR         field    KKR
3     RPS  KXIP        KXIP         field   KXIP
4     RCB    DC         RCB           bat    RCB
..    ...   ...         ...           ...    ...
809   KKR    RR          RR         field    KKR
810    DC   RCB          DC         field     DC
811   SRH    MI         SRH         field    SRH
812    MI    DC          DC         field     MI
813   SRH   RCB         SRH         field    SRH

[814 rows x 5 columns]

In [9]:
#a=['field','bat']
#b=[1,2]
#sample.replace(a,b,inplace = True)
#sample['toss_decision'] = sample['toss_decision'].astype(float)
sample=sample.dropna()
sample

    team1 team2 toss_winner toss_decision winner
0     SRH   RCB         RCB         field    SRH
1      MI   RPS         RPS         field    RPS
2      GL   KKR         KKR         field    KKR
3     RPS  KXIP        KXIP         field   KXIP
4     RCB    DC         RCB           bat    RCB
..    ...   ...         ...           ...    ...
809   KKR    RR          RR         field    KKR
810    DC   RCB          DC         field     DC
811   SRH    MI         SRH         field    SRH
812    MI    DC          DC         field     MI
813   SRH   RCB         SRH         field    SRH

[810 rows x 5 columns]

In [10]:
#white box
#black box

In [11]:
#Tree model visualization

In [12]:
#sns.heatmap(sample.corr())

# PRE-TOSS TRY THIS

In [13]:
sample=old_matches.drop(['id','season','city','date','result','dl_applied','win_by_runs','win_by_wickets','player_of_match','venue','umpire1','umpire2','umpire3'],axis=1)
sample

,team1,team2,toss_winner,toss_decision,winner
0,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad
1,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant
2,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders
3,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab
4,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore
...,...,...,...,...,...
809,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,field,Kolkata Knight Riders
810,Delhi Capitals,Royal Challengers Bangalore,Delhi Capitals,field,Delhi Capitals
811,Sunrisers Hyderabad,Mumbai Indians,Sunrisers Hyderabad,field,Sunrisers Hyderabad
812,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians
813,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,field,Sunrisers Hyderabad

In [14]:
x=['Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
    'Rising Pune Supergiant', 'Royal Challengers Bangalore',
    'Kolkata Knight Riders', 'Delhi Daredevils', 'Kings XI Punjab',
    'Chennai Super Kings', 'Rajasthan Royals', 'Deccan Chargers',
    'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants', 'Delhi Capitals']
#y = [1,2,3,4,5,6,7,8,9,10,11,12,13,4,14]
y = ['SRH','MI','GL','RPS','RCB','KKR','DC','KXIP','CSK','RR','SRH','KTK','PW','RPS','DC']

In [15]:
sample.replace(x,y,inplace = True)
sample
sample=sample.dropna()
sample

    team1 team2 toss_winner toss_decision winner
0     SRH   RCB         RCB         field    SRH
1      MI   RPS         RPS         field    RPS
2      GL   KKR         KKR         field    KKR
3     RPS  KXIP        KXIP         field   KXIP
4     RCB    DC         RCB           bat    RCB
..    ...   ...         ...           ...    ...
809   KKR    RR          RR         field    KKR
810    DC   RCB          DC         field     DC
811   SRH    MI         SRH         field    SRH
812    MI    DC          DC         field     MI
813   SRH   RCB         SRH         field    SRH

[810 rows x 5 columns]

In [16]:
#sample[sample['team1']=='KTK'].drop()

In [17]:
sample = sample[sample.team1 != 'KTK']
sample = sample[sample.team1 != 'RPS']
sample = sample[sample.team1 != 'PW']
sample = sample[sample.team1 != 'GL']
#sample = sample[sample.team1 != 'SRH1']#KTK RPS PW GL
sample

    team1 team2 toss_winner toss_decision winner
0     SRH   RCB         RCB         field    SRH
1      MI   RPS         RPS         field    RPS
4     RCB    DC         RCB           bat    RCB
6     KKR    MI          MI         field     MI
7     RCB  KXIP         RCB           bat   KXIP
..    ...   ...         ...           ...    ...
809   KKR    RR          RR         field    KKR
810    DC   RCB          DC         field     DC
811   SRH    MI         SRH         field    SRH
812    MI    DC          DC         field     MI
813   SRH   RCB         SRH         field    SRH

[754 rows x 5 columns]

In [18]:
sample = sample[sample.team2 != 'KTK']
sample = sample[sample.team2 != 'RPS']
sample = sample[sample.team2 != 'PW']
sample = sample[sample.team2 != 'GL']#KTK RPS PW GL
#sample = sample[sample.team2 != 'SRH1']
sample

    team1 team2 toss_winner toss_decision winner
0     SRH   RCB         RCB         field    SRH
4     RCB    DC         RCB           bat    RCB
6     KKR    MI          MI         field     MI
7     RCB  KXIP         RCB           bat   KXIP
9     SRH    MI          MI         field     MI
..    ...   ...         ...           ...    ...
809   KKR    RR          RR         field    KKR
810    DC   RCB          DC         field     DC
811   SRH    MI         SRH         field    SRH
812    MI    DC          DC         field     MI
813   SRH   RCB         SRH         field    SRH

[696 rows x 5 columns]

In [19]:
#Match Prediction Before Toss

In [20]:
sample

    team1 team2 toss_winner toss_decision winner
0     SRH   RCB         RCB         field    SRH
4     RCB    DC         RCB           bat    RCB
6     KKR    MI          MI         field     MI
7     RCB  KXIP         RCB           bat   KXIP
9     SRH    MI          MI         field     MI
..    ...   ...         ...           ...    ...
809   KKR    RR          RR         field    KKR
810    DC   RCB          DC         field     DC
811   SRH    MI         SRH         field    SRH
812    MI    DC          DC         field     MI
813   SRH   RCB         SRH         field    SRH

[696 rows x 5 columns]

In [21]:
#jkl = sample[((sample.team1 == 'RR')&(sample.team2 == 'SRH'))|((sample.team2 == 'RR')&(sample.team1 == 'SRH'))]#KTK RPS PW GL
#jkl['winner'].value_counts()

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [23]:
sample.dtypes

team1            object
team2            object
toss_winner      object
toss_decision    object
winner           object
dtype: object

In [24]:
sample = pd.get_dummies(sample, prefix=['Team_1', 'Team_2'], columns=['team1', 'team2'])
sample

,toss_winner,toss_decision,winner,Team_1_CSK,Team_1_DC,Team_1_KKR,Team_1_KXIP,Team_1_MI,Team_1_RCB,Team_1_RR,Team_1_SRH,Team_2_CSK,Team_2_DC,Team_2_KKR,Team_2_KXIP,Team_2_MI,Team_2_RCB,Team_2_RR,Team_2_SRH
0,RCB,field,SRH,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0
4,RCB,bat,RCB,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0
6,MI,field,MI,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0
7,RCB,bat,KXIP,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
9,MI,field,MI,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
809,RR,field,KKR,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
810,DC,field,DC,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
811,SRH,field,SRH,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0
812,DC,field,MI,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0
813,SRH,field,SRH,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0

In [25]:
X = sample.drop(['winner','toss_decision','toss_winner'], axis=1)
y = sample["winner"]

In [26]:
#sample = pd.get_dummies(sample, prefix=['Team_1', 'Team_2','toss_win','toss_dec'], columns=['team1', 'team2','toss_winner','toss_decision'])
#X = sample.drop(['winner'], axis=1)
#y = sample["winner"]

In [27]:
# Separate train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
X_train

,Team_1_CSK,Team_1_DC,Team_1_KKR,Team_1_KXIP,Team_1_MI,Team_1_RCB,Team_1_RR,Team_1_SRH,Team_2_CSK,Team_2_DC,Team_2_KKR,Team_2_KXIP,Team_2_MI,Team_2_RCB,Team_2_RR,Team_2_SRH
441,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
780,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
358,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
714,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
205,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
134,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
330,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0
522,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
130,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [28]:
rf = RandomForestClassifier(n_estimators=100,oob_score=True ,class_weight='balanced',verbose=2,n_jobs=-1, max_depth=40,random_state=42)
rf.fit(X_train, y_train)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    0.0s

building tree 1 of 100building tree 2 of 100building tree 3 of 100
building tree 4 of 100
building tree 5 of 100

building tree 6 of 100
building tree 7 of 100
building tree 8 of 100

building tree 9 of 100building tree 10 of 100

building tree 11 of 100
building tree 12 of 100
building tree 13 of 100building tree 14 of 100building tree 15 of 100
building tree 16 of 100


building tree 17 of 100
building tree 18 of 100
building tree 19 of 100building tree 20 of 100building tree 21 of 100


building tree 22 of 100building tree 23 of 100
building tree 24 of 100

building tree 25 of 100
building tree 26 of 100
building tree 27 of 100
building tree 28 of 100building tree 29 of 100

building tree 30 of 100
building tree 31 of 100building tree 32 of 100

building tree 33 of 100building tree 34 of 100

building tree 35 of 100building tree 36 of 100

building tree 37 of 100
building tree 38 of 100
building tree 39 of 100
building tree 40 of 100
building tree 41 of 100
building tree 42 of 100
building tree 43 of 100building tree 44 of 100building tree 45 of 100


building tree 46 of 100
building tree 47 of 100
building tree 48 of 100building tree 49 of 100building tree 50 of 100


building tree 51 of 100
building tree 52 of 100building tree 53 of 100

building tree 54 of 100
building tree 55 of 100building tree 56 of 100
building tree 57 of 100
building tree 58 of 100

building tree 59 of 100
building tree 60 of 100building tree 61 of 100

building tree 62 of 100
building tree 63 of 100
building tree 64 of 100
building tree 65 of 100
building tree 66 of 100building tree 67 of 100

building tree 68 of 100building tree 69 of 100

building tree 70 of 100
building tree 71 of 100
building tree 72 of 100
building tree 73 of 100building tree 74 of 100building tree 75 of 100

building tree 76 of 100building tree 77 of 100


building tree 78 of 100
building tree 79 of 100
building tree 80 of 100
building tree 81 of 100
building tree 82 of 100
building tree 83 of 100
building tree 84 of 100
building tree 85 of 100
building tree 86 of 100
building tree 87 of 100
building tree 88 of 100
building tree 89 of 100
building tree 90 of 100
building tree 91 of 100
building tree 92 of 100
building tree 93 of 100
building tree 94 of 100
building tree 95 of 100
building tree 96 of 100
building tree 97 of 100
building tree 98 of 100
building tree 99 of 100building tree 100 of 100

[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    0.1s finished

RandomForestClassifier(bootstrap=True, class_weight='balanced',
                       criterion='gini', max_depth=40, max_features='auto',
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=True,
                       random_state=42, verbose=2, warm_start=False)

In [29]:
score = rf.score(X_train, y_train)
score2 = rf.score(X_test, y_test)
print(score)
print(score2)

[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  25 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  25 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 100 out of 100 | elapsed:    0.0s finished

0.6406570841889117
0.5023923444976076

In [30]:
print(rf.oob_score_)

0.5400410677618069

In [31]:
copy=pd.read_csv('2020 Copy.csv')
#copy

In [32]:
x=['Sunrisers hyderabad', 'Mumbai indians', 'Gujarat Lions',
    'Rising Pune Supergiant', 'Royal challengers bangalore',
    'Kolkata knight riders', 'Delhi Daredevils', 'Kings xi punjab',
    'Chennai super kings', 'Rajasthan royals', 'Deccan Chargers',
    'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants', 'Delhi capitals','Royal challengers']
#y = [1,2,3,4,5,6,7,8,9,10,11,12,13,4,14]
y = ['SRH','MI','GL','RPS','RCB','KKR','DD','KXIP','CSK','RR','SRH','KTK','PW','RPS','DC','RCB']

copy.replace(x,y,inplace = True)
copy

    Team Team2
0    CSK    RR
1   KXIP    DC
2    KKR   RCB
3     RR   SRH
4    CSK    MI
5    KKR    DC
6   KXIP   SRH
7    RCB   CSK
8     RR    MI
9    KKR  KXIP
10   SRH    DC
11    MI   RCB
12   CSK   KKR
13  KXIP    RR
14    DC    MI
15   RCB   SRH
16   CSK  KXIP
17   KKR    RR
18    DC   RCB
19   SRH    MI
20    MI    DC
21   SRH   RCB
22    DC   SRH
23    MI    DC

In [33]:
copy = pd.get_dummies(copy, prefix=['Team_1', 'Team_2'], columns=['Team', 'Team2'])
copy

,Team_1_CSK,Team_1_DC,Team_1_KKR,Team_1_KXIP,Team_1_MI,Team_1_RCB,Team_1_RR,Team_1_SRH,Team_2_CSK,Team_2_DC,Team_2_KKR,Team_2_KXIP,Team_2_MI,Team_2_RCB,Team_2_RR,Team_2_SRH
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
4,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
5,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0
6,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
7,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0
8,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0
9,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
10,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0
11,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
12,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
13,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
14,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0
15,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
16,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
17,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
18,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
19,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0
20,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0
21,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0
22,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
23,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0

In [34]:
predictions=rf.predict(copy)
print(predictions)

['CSK' 'DC' 'RCB' 'SRH' 'MI' 'DC' 'SRH' 'CSK' 'MI' 'KKR' 'DC' 'MI' 'CSK'
 'RR' 'DC' 'SRH' 'CSK' 'RR' 'RCB' 'SRH' 'DC' 'SRH' 'SRH' 'DC']

[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  25 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 100 out of 100 | elapsed:    0.0s finished

In [35]:
pre = pd.DataFrame(predictions,columns=['Possible Winners'])
#pre

In [36]:
pre['Possible Winners'].value_counts()

SRH    6
DC     6
CSK    4
MI     3
RCB    2
RR     2
KKR    1
Name: Possible Winners, dtype: int64

# AFTER TOSS USE BELOW

In [37]:
#Match Prediction after Toss

In [38]:
sample1=old_matches.drop(['id','season','city','date','result','dl_applied','win_by_runs','win_by_wickets','player_of_match','venue','umpire1','umpire2','umpire3'],axis=1)
sample1

,team1,team2,toss_winner,toss_decision,winner
0,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad
1,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant
2,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders
3,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab
4,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore
...,...,...,...,...,...
809,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,field,Kolkata Knight Riders
810,Delhi Capitals,Royal Challengers Bangalore,Delhi Capitals,field,Delhi Capitals
811,Sunrisers Hyderabad,Mumbai Indians,Sunrisers Hyderabad,field,Sunrisers Hyderabad
812,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians
813,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,field,Sunrisers Hyderabad

In [39]:
x=['Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
    'Rising Pune Supergiant', 'Royal Challengers Bangalore',
    'Kolkata Knight Riders', 'Delhi Daredevils', 'Kings XI Punjab',
    'Chennai Super Kings', 'Rajasthan Royals', 'Deccan Chargers',
    'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants', 'Delhi Capitals']
#y = [1,2,3,4,5,6,7,8,9,10,11,12,13,4,14]
y = ['SRH','MI','GL','RPS','RCB','KKR','DC','KXIP','CSK','RR','SRH1','KTK','PW','RPS','DC']

sample1.replace(x,y,inplace = True)
sample1

    team1 team2 toss_winner toss_decision winner
0     SRH   RCB         RCB         field    SRH
1      MI   RPS         RPS         field    RPS
2      GL   KKR         KKR         field    KKR
3     RPS  KXIP        KXIP         field   KXIP
4     RCB    DC         RCB           bat    RCB
..    ...   ...         ...           ...    ...
809   KKR    RR          RR         field    KKR
810    DC   RCB          DC         field     DC
811   SRH    MI         SRH         field    SRH
812    MI    DC          DC         field     MI
813   SRH   RCB         SRH         field    SRH

[814 rows x 5 columns]

In [40]:
sample1=sample1.dropna()
sample1

    team1 team2 toss_winner toss_decision winner
0     SRH   RCB         RCB         field    SRH
1      MI   RPS         RPS         field    RPS
2      GL   KKR         KKR         field    KKR
3     RPS  KXIP        KXIP         field   KXIP
4     RCB    DC         RCB           bat    RCB
..    ...   ...         ...           ...    ...
809   KKR    RR          RR         field    KKR
810    DC   RCB          DC         field     DC
811   SRH    MI         SRH         field    SRH
812    MI    DC          DC         field     MI
813   SRH   RCB         SRH         field    SRH

[810 rows x 5 columns]

In [41]:
sample1 = sample1[sample1.team1 != 'KTK']
sample1 = sample1[sample1.team1 != 'RPS']
sample1 = sample1[sample1.team1 != 'PW']
sample1 = sample1[sample1.team1 != 'GL']
sample1 = sample1[sample1.team1 != 'SRH1']
#sample1 = sample1[sample1.team1 != 'DC1']#KTK RPS PW GL
sample1

    team1 team2 toss_winner toss_decision winner
0     SRH   RCB         RCB         field    SRH
1      MI   RPS         RPS         field    RPS
4     RCB    DC         RCB           bat    RCB
6     KKR    MI          MI         field     MI
7     RCB  KXIP         RCB           bat   KXIP
..    ...   ...         ...           ...    ...
809   KKR    RR          RR         field    KKR
810    DC   RCB          DC         field     DC
811   SRH    MI         SRH         field    SRH
812    MI    DC          DC         field     MI
813   SRH   RCB         SRH         field    SRH

[711 rows x 5 columns]

In [42]:
sample1 = sample1[sample1.team2 != 'KTK']
sample1 = sample1[sample1.team2 != 'RPS']
sample1 = sample1[sample1.team2 != 'PW']
sample1 = sample1[sample1.team2 != 'GL']
sample1 = sample1[sample1.team2 != 'SRH1']
#sample1 = sample1[sample1.team2 != 'DC1']#KTK RPS PW GL
sample1

    team1 team2 toss_winner toss_decision winner
0     SRH   RCB         RCB         field    SRH
4     RCB    DC         RCB           bat    RCB
6     KKR    MI          MI         field     MI
7     RCB  KXIP         RCB           bat   KXIP
9     SRH    MI          MI         field     MI
..    ...   ...         ...           ...    ...
809   KKR    RR          RR         field    KKR
810    DC   RCB          DC         field     DC
811   SRH    MI         SRH         field    SRH
812    MI    DC          DC         field     MI
813   SRH   RCB         SRH         field    SRH

[626 rows x 5 columns]

In [43]:
sample1

    team1 team2 toss_winner toss_decision winner
0     SRH   RCB         RCB         field    SRH
4     RCB    DC         RCB           bat    RCB
6     KKR    MI          MI         field     MI
7     RCB  KXIP         RCB           bat   KXIP
9     SRH    MI          MI         field     MI
..    ...   ...         ...           ...    ...
809   KKR    RR          RR         field    KKR
810    DC   RCB          DC         field     DC
811   SRH    MI         SRH         field    SRH
812    MI    DC          DC         field     MI
813   SRH   RCB         SRH         field    SRH

[626 rows x 5 columns]

In [44]:
#sample1[(sample1['team1']=='SRH')& (sample1['team2']=='RR')|(sample1['team2']=='SRH')& (sample1['team1']=='RR') ]

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [46]:
sampl = pd.get_dummies(sample1, prefix=['Team_1', 'Team_2','toss_won','toss_dec'], 
                        columns=['team1', 'team2','toss_winner','toss_decision'])
sampl

,winner,Team_1_CSK,Team_1_DC,Team_1_KKR,Team_1_KXIP,Team_1_MI,Team_1_RCB,Team_1_RR,Team_1_SRH,Team_2_CSK,...,toss_won_CSK,toss_won_DC,toss_won_KKR,toss_won_KXIP,toss_won_MI,toss_won_RCB,toss_won_RR,toss_won_SRH,toss_dec_bat,toss_dec_field
0,SRH,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,1
4,RCB,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,1,0
6,MI,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
7,KXIP,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,1,0
9,MI,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
809,KKR,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
810,DC,0,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
811,SRH,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,1
812,MI,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
813,SRH,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,1

In [47]:
X = sampl.drop(['winner'], axis=1)
y = sampl["winner"]

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
X_train

,Team_1_CSK,Team_1_DC,Team_1_KKR,Team_1_KXIP,Team_1_MI,Team_1_RCB,Team_1_RR,Team_1_SRH,Team_2_CSK,Team_2_DC,...,toss_won_CSK,toss_won_DC,toss_won_KKR,toss_won_KXIP,toss_won_MI,toss_won_RCB,toss_won_RR,toss_won_SRH,toss_dec_bat,toss_dec_field
657,0,0,0,1,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,1
11,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
156,0,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
169,0,0,0,0,1,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,1
665,1,0,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
159,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,1,0
420,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
612,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,1
153,0,0,1,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,1

In [49]:
rf1 = RandomForestClassifier(n_estimators=307, max_depth=50,oob_score=True ,class_weight='balanced',verbose=2,n_jobs=1,random_state=42)
rf1.fit(X_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s

building tree 1 of 307
building tree 2 of 307
building tree 3 of 307
building tree 4 of 307
building tree 5 of 307
building tree 6 of 307
building tree 7 of 307
building tree 8 of 307
building tree 9 of 307
building tree 10 of 307
building tree 11 of 307
building tree 12 of 307
building tree 13 of 307
building tree 14 of 307
building tree 15 of 307
building tree 16 of 307
building tree 17 of 307
building tree 18 of 307
building tree 19 of 307
building tree 20 of 307
building tree 21 of 307
building tree 22 of 307
building tree 23 of 307
building tree 24 of 307
building tree 25 of 307
building tree 26 of 307
building tree 27 of 307
building tree 28 of 307
building tree 29 of 307
building tree 30 of 307
building tree 31 of 307
building tree 32 of 307
building tree 33 of 307
building tree 34 of 307
building tree 35 of 307
building tree 36 of 307
building tree 37 of 307
building tree 38 of 307
building tree 39 of 307
building tree 40 of 307
building tree 41 of 307
building tree 42 of 307
building tree 43 of 307
building tree 44 of 307
building tree 45 of 307
building tree 46 of 307
building tree 47 of 307
building tree 48 of 307
building tree 49 of 307
building tree 50 of 307
building tree 51 of 307
building tree 52 of 307
building tree 53 of 307
building tree 54 of 307
building tree 55 of 307
building tree 56 of 307
building tree 57 of 307
building tree 58 of 307
building tree 59 of 307
building tree 60 of 307
building tree 61 of 307
building tree 62 of 307
building tree 63 of 307
building tree 64 of 307
building tree 65 of 307
building tree 66 of 307
building tree 67 of 307
building tree 68 of 307
building tree 69 of 307
building tree 70 of 307
building tree 71 of 307
building tree 72 of 307
building tree 73 of 307
building tree 74 of 307
building tree 75 of 307
building tree 76 of 307
building tree 77 of 307
building tree 78 of 307
building tree 79 of 307
building tree 80 of 307
building tree 81 of 307
building tree 82 of 307
building tree 83 of 307
building tree 84 of 307
building tree 85 of 307
building tree 86 of 307
building tree 87 of 307
building tree 88 of 307
building tree 89 of 307
building tree 90 of 307
building tree 91 of 307
building tree 92 of 307
building tree 93 of 307
building tree 94 of 307
building tree 95 of 307
building tree 96 of 307
building tree 97 of 307
building tree 98 of 307
building tree 99 of 307
building tree 100 of 307
building tree 101 of 307
building tree 102 of 307
building tree 103 of 307
building tree 104 of 307
building tree 105 of 307
building tree 106 of 307
building tree 107 of 307
building tree 108 of 307
building tree 109 of 307
building tree 110 of 307
building tree 111 of 307
building tree 112 of 307
building tree 113 of 307
building tree 114 of 307
building tree 115 of 307
building tree 116 of 307
building tree 117 of 307
building tree 118 of 307
building tree 119 of 307
building tree 120 of 307
building tree 121 of 307
building tree 122 of 307
building tree 123 of 307
building tree 124 of 307
building tree 125 of 307
building tree 126 of 307
building tree 127 of 307
building tree 128 of 307
building tree 129 of 307
building tree 130 of 307
building tree 131 of 307
building tree 132 of 307
building tree 133 of 307
building tree 134 of 307
building tree 135 of 307
building tree 136 of 307
building tree 137 of 307
building tree 138 of 307
building tree 139 of 307
building tree 140 of 307
building tree 141 of 307
building tree 142 of 307
building tree 143 of 307
building tree 144 of 307
building tree 145 of 307
building tree 146 of 307
building tree 147 of 307
building tree 148 of 307
building tree 149 of 307
building tree 150 of 307
building tree 151 of 307
building tree 152 of 307
building tree 153 of 307
building tree 154 of 307
building tree 155 of 307
building tree 156 of 307
building tree 157 of 307
building tree 158 of 307
building tree 159 of 307
building tree 160 of 307
building tree 161 of 307
building tree 162 of 307
building tree 163 of 307
building tree 164 of 307
building tree 165 of 307
building tree 166 of 307
building tree 167 of 307
building tree 168 of 307
building tree 169 of 307
building tree 170 of 307
building tree 171 of 307
building tree 172 of 307
building tree 173 of 307
building tree 174 of 307
building tree 175 of 307
building tree 176 of 307
building tree 177 of 307
building tree 178 of 307
building tree 179 of 307
building tree 180 of 307
building tree 181 of 307
building tree 182 of 307
building tree 183 of 307
building tree 184 of 307
building tree 185 of 307
building tree 186 of 307
building tree 187 of 307
building tree 188 of 307
building tree 189 of 307
building tree 190 of 307
building tree 191 of 307
building tree 192 of 307
building tree 193 of 307
building tree 194 of 307
building tree 195 of 307
building tree 196 of 307
building tree 197 of 307
building tree 198 of 307
building tree 199 of 307
building tree 200 of 307
building tree 201 of 307
building tree 202 of 307
building tree 203 of 307
building tree 204 of 307
building tree 205 of 307
building tree 206 of 307
building tree 207 of 307
building tree 208 of 307
building tree 209 of 307
building tree 210 of 307
building tree 211 of 307
building tree 212 of 307
building tree 213 of 307
building tree 214 of 307
building tree 215 of 307
building tree 216 of 307
building tree 217 of 307
building tree 218 of 307
building tree 219 of 307
building tree 220 of 307
building tree 221 of 307
building tree 222 of 307
building tree 223 of 307
building tree 224 of 307
building tree 225 of 307
building tree 226 of 307
building tree 227 of 307
building tree 228 of 307
building tree 229 of 307
building tree 230 of 307
building tree 231 of 307
building tree 232 of 307
building tree 233 of 307
building tree 234 of 307
building tree 235 of 307
building tree 236 of 307
building tree 237 of 307
building tree 238 of 307
building tree 239 of 307
building tree 240 of 307
building tree 241 of 307
building tree 242 of 307
building tree 243 of 307
building tree 244 of 307
building tree 245 of 307
building tree 246 of 307
building tree 247 of 307
building tree 248 of 307
building tree 249 of 307
building tree 250 of 307
building tree 251 of 307
building tree 252 of 307
building tree 253 of 307
building tree 254 of 307
building tree 255 of 307
building tree 256 of 307
building tree 257 of 307
building tree 258 of 307
building tree 259 of 307
building tree 260 of 307
building tree 261 of 307
building tree 262 of 307
building tree 263 of 307
building tree 264 of 307
building tree 265 of 307
building tree 266 of 307
building tree 267 of 307
building tree 268 of 307
building tree 269 of 307
building tree 270 of 307
building tree 271 of 307
building tree 272 of 307
building tree 273 of 307
building tree 274 of 307
building tree 275 of 307
building tree 276 of 307
building tree 277 of 307
building tree 278 of 307
building tree 279 of 307
building tree 280 of 307
building tree 281 of 307
building tree 282 of 307
building tree 283 of 307
building tree 284 of 307
building tree 285 of 307
building tree 286 of 307
building tree 287 of 307
building tree 288 of 307
building tree 289 of 307
building tree 290 of 307
building tree 291 of 307
building tree 292 of 307
building tree 293 of 307
building tree 294 of 307
building tree 295 of 307
building tree 296 of 307
building tree 297 of 307
building tree 298 of 307
building tree 299 of 307
building tree 300 of 307
building tree 301 of 307
building tree 302 of 307
building tree 303 of 307
building tree 304 of 307
building tree 305 of 307
building tree 306 of 307
building tree 307 of 307

[Parallel(n_jobs=1)]: Done 307 out of 307 | elapsed:    0.3s finished

RandomForestClassifier(bootstrap=True, class_weight='balanced',
                       criterion='gini', max_depth=50, max_features='auto',
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=307, n_jobs=1, oob_score=True,
                       random_state=42, verbose=2, warm_start=False)

In [50]:
score = rf1.score(X_train, y_train)
score2 = rf1.score(X_test, y_test)
print(score)
print(score2)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 307 out of 307 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 307 out of 307 | elapsed:    0.0s finished

0.7
0.5238095238095238

In [51]:
print(rf1.oob_score_)

0.534

In [52]:
#after training now applying 2020 schedule to predict

In [70]:
copy3=pd.read_csv('2020 Copy3.csv')
#copy3

In [71]:
x=['Sunrisers hyderabad', 'Mumbai indians', 'Gujarat Lions',
    'Rising Pune Supergiant', 'Royal challengers bangalore',
    'Kolkata knight riders', 'Delhi Daredevils', 'Kings xi punjab',
    'Chennai super kings', 'Rajasthan royals', 'Deccan Chargers',
    'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants', 'Delhi capitals','Royal challengers']
#y = [1,2,3,4,5,6,7,8,9,10,11,12,13,4,14]
y = ['SRH','MI','GL','RPS','RCB','KKR','DD','KXIP','CSK','RR','DCR','KTK','PW','RPS','DC','RCB']

copy3.replace(x,y,inplace = True)
copy3

    Team Team2 toss_winner toss_decision
0    CSK    RR          RR           bat
1   KXIP    DC          DC           bat
2    KKR   RCB         RCB           bat
3     RR   SRH         SRH         field
4    CSK    MI          MI         field
5    KKR    DC         KKR         field
6   KXIP   SRH         SRH           bat
7    RCB   CSK         RCB           bat
8     RR    MI          MI           bat
9    KKR  KXIP        KXIP         field
10   SRH    DC          DC         field
11    MI   RCB          MI         field
12   CSK   KKR         CSK         field
13  KXIP    RR          RR         field
14    DC    MI          MI         field
15   RCB   SRH         SRH         field
16   CSK  KXIP         CSK         field
17   KKR    RR          RR         field
18    DC   RCB          DC         field
19   SRH    MI         SRH         field
20    MI    DC          MI           bat
21   SRH   RCB         SRH         field
22    DC   SRH          DC           bat
23    MI    DC          DC           bat

In [72]:
copyy = pd.get_dummies(copy3, prefix=['Team_1', 'Team_2','toss_won','toss_dec'], columns=['Team', 'Team2','toss_winner','toss_decision'])
copyy

,Team_1_CSK,Team_1_DC,Team_1_KKR,Team_1_KXIP,Team_1_MI,Team_1_RCB,Team_1_RR,Team_1_SRH,Team_2_CSK,Team_2_DC,...,toss_won_CSK,toss_won_DC,toss_won_KKR,toss_won_KXIP,toss_won_MI,toss_won_RCB,toss_won_RR,toss_won_SRH,toss_dec_bat,toss_dec_field
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
1,0,0,0,1,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,1,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
3,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,1
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
5,0,0,1,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,1
6,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0
7,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,0,1,0,0,1,0
8,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0
9,0,0,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
10,0,0,0,0,0,0,0,1,0,1,...,0,1,0,0,0,0,0,0,0,1
11,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
12,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
13,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
14,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
15,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
16,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
17,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
18,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
19,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,1
20,0,0,0,0,1,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,0
21,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,1
22,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
23,0,0,0,0,1,0,0,0,0,1,...,0,1,0,0,0,0,0,0,1,0

In [73]:
predicts=rf1.predict(copyy)
print(predicts)

['CSK' 'KXIP' 'RCB' 'SRH' 'MI' 'KKR' 'SRH' 'CSK' 'RR' 'KKR' 'DC' 'MI'
 'CSK' 'KXIP' 'DC' 'SRH' 'CSK' 'RR' 'DC' 'SRH' 'MI' 'SRH' 'SRH' 'MI']

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 307 out of 307 | elapsed:    0.0s finished

In [57]:
prs=rf1.predict(X_test)
#print(prs)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 307 out of 307 | elapsed:    0.0s finished

In [66]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, prs))

Accuracy: 0.5238095238095238

In [67]:
pr = pd.DataFrame(predicts,columns=['Possible_aft_toss_Winners'])
#pr

In [127]:
pr['Possible_aft_toss_Winners'].value_counts()

SRH     4
CSK     3
RR      3
DC      3
MI      2
KXIP    2
RCB     2
KKR     1
Name: Possible_aft_toss_Winners, dtype: int64

In [128]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,prs)
cm

array([[16,  3,  1,  1,  0,  0,  1,  3],
       [ 0,  5,  2,  0,  2,  1,  1,  0],
       [ 2,  1,  8,  1,  0,  0,  2,  2],
       [ 1,  1,  1,  6,  0,  2,  0,  0],
       [ 6,  0,  0,  1, 14,  6,  1,  0],
       [ 0,  0,  1,  1,  0,  5,  3,  1],
       [ 0,  3,  1,  1,  1,  0,  3,  0],
       [ 0,  1,  0,  0,  2,  0,  1,  9]], dtype=int64)

In [63]:
from sklearn.model_selection import cross_val_score
RF_accuracies = cross_val_score(estimator = rf1, X = X_test, y = y_test, cv = 5)
print("Mean_RF_Acc : ", RF_accuracies.mean())

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s

building tree 1 of 307
building tree 2 of 307
building tree 3 of 307
building tree 4 of 307
building tree 5 of 307
building tree 6 of 307
building tree 7 of 307
building tree 8 of 307
building tree 9 of 307
building tree 10 of 307
building tree 11 of 307
building tree 12 of 307
building tree 13 of 307
building tree 14 of 307
building tree 15 of 307
building tree 16 of 307
building tree 17 of 307
building tree 18 of 307
building tree 19 of 307
building tree 20 of 307
building tree 21 of 307
building tree 22 of 307
building tree 23 of 307
building tree 24 of 307
building tree 25 of 307
building tree 26 of 307
building tree 27 of 307
building tree 28 of 307
building tree 29 of 307
building tree 30 of 307
building tree 31 of 307
building tree 32 of 307
building tree 33 of 307
building tree 34 of 307
building tree 35 of 307
building tree 36 of 307
building tree 37 of 307
building tree 38 of 307
building tree 39 of 307
building tree 40 of 307
building tree 41 of 307
building tree 42 of 307
building tree 43 of 307
building tree 44 of 307
building tree 45 of 307
building tree 46 of 307
building tree 47 of 307
building tree 48 of 307
building tree 49 of 307
building tree 50 of 307
building tree 51 of 307
building tree 52 of 307
building tree 53 of 307
building tree 54 of 307
building tree 55 of 307
building tree 56 of 307
building tree 57 of 307
building tree 58 of 307
building tree 59 of 307
building tree 60 of 307
building tree 61 of 307
building tree 62 of 307
building tree 63 of 307
building tree 64 of 307
building tree 65 of 307
building tree 66 of 307
building tree 67 of 307
building tree 68 of 307
building tree 69 of 307
building tree 70 of 307
building tree 71 of 307
building tree 72 of 307
building tree 73 of 307
building tree 74 of 307
building tree 75 of 307
building tree 76 of 307
building tree 77 of 307
building tree 78 of 307
building tree 79 of 307
building tree 80 of 307
building tree 81 of 307
building tree 82 of 307
building tree 83 of 307
building tree 84 of 307
building tree 85 of 307
building tree 86 of 307
building tree 87 of 307
building tree 88 of 307
building tree 89 of 307
building tree 90 of 307
building tree 91 of 307
building tree 92 of 307
building tree 93 of 307
building tree 94 of 307
building tree 95 of 307
building tree 96 of 307
building tree 97 of 307
building tree 98 of 307
building tree 99 of 307
building tree 100 of 307
building tree 101 of 307
building tree 102 of 307
building tree 103 of 307
building tree 104 of 307
building tree 105 of 307
building tree 106 of 307
building tree 107 of 307
building tree 108 of 307
building tree 109 of 307
building tree 110 of 307
building tree 111 of 307
building tree 112 of 307
building tree 113 of 307
building tree 114 of 307
building tree 115 of 307
building tree 116 of 307
building tree 117 of 307
building tree 118 of 307
building tree 119 of 307
building tree 120 of 307
building tree 121 of 307
building tree 122 of 307
building tree 123 of 307
building tree 124 of 307
building tree 125 of 307
building tree 126 of 307
building tree 127 of 307
building tree 128 of 307
building tree 129 of 307
building tree 130 of 307
building tree 131 of 307
building tree 132 of 307
building tree 133 of 307
building tree 134 of 307
building tree 135 of 307
building tree 136 of 307
building tree 137 of 307
building tree 138 of 307
building tree 139 of 307
building tree 140 of 307
building tree 141 of 307
building tree 142 of 307
building tree 143 of 307
building tree 144 of 307
building tree 145 of 307
building tree 146 of 307
building tree 147 of 307
building tree 148 of 307
building tree 149 of 307
building tree 150 of 307
building tree 151 of 307
building tree 152 of 307
building tree 153 of 307
building tree 154 of 307
building tree 155 of 307
building tree 156 of 307
building tree 157 of 307
building tree 158 of 307
building tree 159 of 307
building tree 160 of 307
building tree 161 of 307
building tree 162 of 307
building tree 163 of 307
building tree 164 of 307
building tree 165 of 307
building tree 166 of 307
building tree 167 of 307
building tree 168 of 307
building tree 169 of 307
building tree 170 of 307
building tree 171 of 307
building tree 172 of 307
building tree 173 of 307
building tree 174 of 307
building tree 175 of 307
building tree 176 of 307
building tree 177 of 307
building tree 178 of 307
building tree 179 of 307
building tree 180 of 307
building tree 181 of 307
building tree 182 of 307
building tree 183 of 307
building tree 184 of 307
building tree 185 of 307
building tree 186 of 307
building tree 187 of 307
building tree 188 of 307
building tree 189 of 307
building tree 190 of 307
building tree 191 of 307
building tree 192 of 307
building tree 193 of 307
building tree 194 of 307
building tree 195 of 307
building tree 196 of 307
building tree 197 of 307
building tree 198 of 307
building tree 199 of 307
building tree 200 of 307
building tree 201 of 307
building tree 202 of 307
building tree 203 of 307
building tree 204 of 307
building tree 205 of 307
building tree 206 of 307
building tree 207 of 307
building tree 208 of 307
building tree 209 of 307
building tree 210 of 307
building tree 211 of 307
building tree 212 of 307
building tree 213 of 307
building tree 214 of 307
building tree 215 of 307
building tree 216 of 307
building tree 217 of 307
building tree 218 of 307
building tree 219 of 307
building tree 220 of 307
building tree 221 of 307
building tree 222 of 307
building tree 223 of 307
building tree 224 of 307
building tree 225 of 307
building tree 226 of 307
building tree 227 of 307
building tree 228 of 307
building tree 229 of 307
building tree 230 of 307
building tree 231 of 307
building tree 232 of 307
building tree 233 of 307
building tree 234 of 307
building tree 235 of 307
building tree 236 of 307
building tree 237 of 307
building tree 238 of 307
building tree 239 of 307
building tree 240 of 307
building tree 241 of 307
building tree 242 of 307
building tree 243 of 307
building tree 244 of 307
building tree 245 of 307
building tree 246 of 307
building tree 247 of 307
building tree 248 of 307
building tree 249 of 307
building tree 250 of 307
building tree 251 of 307
building tree 252 of 307
building tree 253 of 307
building tree 254 of 307
building tree 255 of 307
building tree 256 of 307
building tree 257 of 307
building tree 258 of 307
building tree 259 of 307
building tree 260 of 307
building tree 261 of 307
building tree 262 of 307
building tree 263 of 307
building tree 264 of 307
building tree 265 of 307
building tree 266 of 307
building tree 267 of 307
building tree 268 of 307
building tree 269 of 307
building tree 270 of 307
building tree 271 of 307
building tree 272 of 307
building tree 273 of 307
building tree 274 of 307
building tree 275 of 307
building tree 276 of 307
building tree 277 of 307
building tree 278 of 307
building tree 279 of 307
building tree 280 of 307
building tree 281 of 307
building tree 282 of 307
building tree 283 of 307
building tree 284 of 307
building tree 285 of 307
building tree 286 of 307
building tree 287 of 307
building tree 288 of 307
building tree 289 of 307
building tree 290 of 307
building tree 291 of 307
building tree 292 of 307
building tree 293 of 307
building tree 294 of 307
building tree 295 of 307
building tree 296 of 307
building tree 297 of 307
building tree 298 of 307
building tree 299 of 307
building tree 300 of 307
building tree 301 of 307
building tree 302 of 307
building tree 303 of 307
building tree 304 of 307
building tree 305 of 307
building tree 306 of 307
building tree 307 of 307

[Parallel(n_jobs=1)]: Done 307 out of 307 | elapsed:    0.3s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 307 out of 307 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s

building tree 1 of 307
building tree 2 of 307
building tree 3 of 307
building tree 4 of 307
building tree 5 of 307
building tree 6 of 307
building tree 7 of 307
building tree 8 of 307
building tree 9 of 307
building tree 10 of 307
building tree 11 of 307
building tree 12 of 307
building tree 13 of 307
building tree 14 of 307
building tree 15 of 307
building tree 16 of 307
building tree 17 of 307
building tree 18 of 307
building tree 19 of 307
building tree 20 of 307
building tree 21 of 307
building tree 22 of 307
building tree 23 of 307
building tree 24 of 307
building tree 25 of 307
building tree 26 of 307
building tree 27 of 307
building tree 28 of 307
building tree 29 of 307
building tree 30 of 307
building tree 31 of 307
building tree 32 of 307
building tree 33 of 307
building tree 34 of 307
building tree 35 of 307
building tree 36 of 307
building tree 37 of 307
building tree 38 of 307
building tree 39 of 307
building tree 40 of 307
building tree 41 of 307
building tree 42 of 307
building tree 43 of 307
building tree 44 of 307
building tree 45 of 307
building tree 46 of 307
building tree 47 of 307
building tree 48 of 307
building tree 49 of 307
building tree 50 of 307
building tree 51 of 307
building tree 52 of 307
building tree 53 of 307
building tree 54 of 307
building tree 55 of 307
building tree 56 of 307
building tree 57 of 307
building tree 58 of 307
building tree 59 of 307
building tree 60 of 307
building tree 61 of 307
building tree 62 of 307
building tree 63 of 307
building tree 64 of 307
building tree 65 of 307
building tree 66 of 307
building tree 67 of 307
building tree 68 of 307
building tree 69 of 307
building tree 70 of 307
building tree 71 of 307
building tree 72 of 307
building tree 73 of 307
building tree 74 of 307
building tree 75 of 307
building tree 76 of 307
building tree 77 of 307
building tree 78 of 307
building tree 79 of 307
building tree 80 of 307
building tree 81 of 307
building tree 82 of 307
building tree 83 of 307
building tree 84 of 307
building tree 85 of 307
building tree 86 of 307
building tree 87 of 307
building tree 88 of 307
building tree 89 of 307
building tree 90 of 307
building tree 91 of 307
building tree 92 of 307
building tree 93 of 307
building tree 94 of 307
building tree 95 of 307
building tree 96 of 307
building tree 97 of 307
building tree 98 of 307
building tree 99 of 307
building tree 100 of 307
building tree 101 of 307
building tree 102 of 307
building tree 103 of 307
building tree 104 of 307
building tree 105 of 307
building tree 106 of 307
building tree 107 of 307
building tree 108 of 307
building tree 109 of 307
building tree 110 of 307
building tree 111 of 307
building tree 112 of 307
building tree 113 of 307
building tree 114 of 307
building tree 115 of 307
building tree 116 of 307
building tree 117 of 307
building tree 118 of 307
building tree 119 of 307
building tree 120 of 307
building tree 121 of 307
building tree 122 of 307
building tree 123 of 307
building tree 124 of 307
building tree 125 of 307
building tree 126 of 307
building tree 127 of 307
building tree 128 of 307
building tree 129 of 307
building tree 130 of 307
building tree 131 of 307
building tree 132 of 307
building tree 133 of 307
building tree 134 of 307
building tree 135 of 307
building tree 136 of 307
building tree 137 of 307
building tree 138 of 307
building tree 139 of 307
building tree 140 of 307
building tree 141 of 307
building tree 142 of 307
building tree 143 of 307
building tree 144 of 307
building tree 145 of 307
building tree 146 of 307
building tree 147 of 307
building tree 148 of 307
building tree 149 of 307
building tree 150 of 307
building tree 151 of 307
building tree 152 of 307
building tree 153 of 307
building tree 154 of 307
building tree 155 of 307
building tree 156 of 307
building tree 157 of 307
building tree 158 of 307
building tree 159 of 307
building tree 160 of 307
building tree 161 of 307
building tree 162 of 307
building tree 163 of 307
building tree 164 of 307
building tree 165 of 307
building tree 166 of 307
building tree 167 of 307
building tree 168 of 307
building tree 169 of 307
building tree 170 of 307
building tree 171 of 307
building tree 172 of 307
building tree 173 of 307
building tree 174 of 307
building tree 175 of 307
building tree 176 of 307
building tree 177 of 307
building tree 178 of 307
building tree 179 of 307
building tree 180 of 307
building tree 181 of 307
building tree 182 of 307
building tree 183 of 307
building tree 184 of 307
building tree 185 of 307
building tree 186 of 307
building tree 187 of 307
building tree 188 of 307
building tree 189 of 307
building tree 190 of 307
building tree 191 of 307
building tree 192 of 307
building tree 193 of 307
building tree 194 of 307
building tree 195 of 307
building tree 196 of 307
building tree 197 of 307
building tree 198 of 307
building tree 199 of 307
building tree 200 of 307
building tree 201 of 307
building tree 202 of 307
building tree 203 of 307
building tree 204 of 307
building tree 205 of 307
building tree 206 of 307
building tree 207 of 307
building tree 208 of 307
building tree 209 of 307
building tree 210 of 307
building tree 211 of 307
building tree 212 of 307
building tree 213 of 307
building tree 214 of 307
building tree 215 of 307
building tree 216 of 307
building tree 217 of 307
building tree 218 of 307
building tree 219 of 307
building tree 220 of 307
building tree 221 of 307
building tree 222 of 307
building tree 223 of 307
building tree 224 of 307
building tree 225 of 307
building tree 226 of 307
building tree 227 of 307
building tree 228 of 307
building tree 229 of 307
building tree 230 of 307
building tree 231 of 307
building tree 232 of 307
building tree 233 of 307
building tree 234 of 307
building tree 235 of 307
building tree 236 of 307
building tree 237 of 307
building tree 238 of 307
building tree 239 of 307
building tree 240 of 307
building tree 241 of 307
building tree 242 of 307
building tree 243 of 307
building tree 244 of 307
building tree 245 of 307
building tree 246 of 307
building tree 247 of 307
building tree 248 of 307
building tree 249 of 307
building tree 250 of 307
building tree 251 of 307
building tree 252 of 307
building tree 253 of 307
building tree 254 of 307
building tree 255 of 307
building tree 256 of 307
building tree 257 of 307
building tree 258 of 307
building tree 259 of 307
building tree 260 of 307
building tree 261 of 307
building tree 262 of 307
building tree 263 of 307
building tree 264 of 307
building tree 265 of 307
building tree 266 of 307
building tree 267 of 307
building tree 268 of 307
building tree 269 of 307
building tree 270 of 307
building tree 271 of 307
building tree 272 of 307
building tree 273 of 307
building tree 274 of 307
building tree 275 of 307
building tree 276 of 307
building tree 277 of 307
building tree 278 of 307
building tree 279 of 307
building tree 280 of 307
building tree 281 of 307
building tree 282 of 307
building tree 283 of 307
building tree 284 of 307
building tree 285 of 307
building tree 286 of 307
building tree 287 of 307
building tree 288 of 307
building tree 289 of 307
building tree 290 of 307
building tree 291 of 307
building tree 292 of 307
building tree 293 of 307
building tree 294 of 307
building tree 295 of 307
building tree 296 of 307
building tree 297 of 307
building tree 298 of 307
building tree 299 of 307
building tree 300 of 307
building tree 301 of 307
building tree 302 of 307
building tree 303 of 307
building tree 304 of 307
building tree 305 of 307
building tree 306 of 307
building tree 307 of 307

[Parallel(n_jobs=1)]: Done 307 out of 307 | elapsed:    0.3s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 307 out of 307 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s

building tree 1 of 307
building tree 2 of 307
building tree 3 of 307
building tree 4 of 307
building tree 5 of 307
building tree 6 of 307
building tree 7 of 307
building tree 8 of 307
building tree 9 of 307
building tree 10 of 307
building tree 11 of 307
building tree 12 of 307
building tree 13 of 307
building tree 14 of 307
building tree 15 of 307
building tree 16 of 307
building tree 17 of 307
building tree 18 of 307
building tree 19 of 307
building tree 20 of 307
building tree 21 of 307
building tree 22 of 307
building tree 23 of 307
building tree 24 of 307
building tree 25 of 307
building tree 26 of 307
building tree 27 of 307
building tree 28 of 307
building tree 29 of 307
building tree 30 of 307
building tree 31 of 307
building tree 32 of 307
building tree 33 of 307
building tree 34 of 307
building tree 35 of 307
building tree 36 of 307
building tree 37 of 307
building tree 38 of 307
building tree 39 of 307
building tree 40 of 307
building tree 41 of 307
building tree 42 of 307
building tree 43 of 307
building tree 44 of 307
building tree 45 of 307
building tree 46 of 307
building tree 47 of 307
building tree 48 of 307
building tree 49 of 307
building tree 50 of 307
building tree 51 of 307
building tree 52 of 307
building tree 53 of 307
building tree 54 of 307
building tree 55 of 307
building tree 56 of 307
building tree 57 of 307
building tree 58 of 307
building tree 59 of 307
building tree 60 of 307
building tree 61 of 307
building tree 62 of 307
building tree 63 of 307
building tree 64 of 307
building tree 65 of 307
building tree 66 of 307
building tree 67 of 307
building tree 68 of 307
building tree 69 of 307
building tree 70 of 307
building tree 71 of 307
building tree 72 of 307
building tree 73 of 307
building tree 74 of 307
building tree 75 of 307
building tree 76 of 307
building tree 77 of 307
building tree 78 of 307
building tree 79 of 307
building tree 80 of 307
building tree 81 of 307
building tree 82 of 307
building tree 83 of 307
building tree 84 of 307
building tree 85 of 307
building tree 86 of 307
building tree 87 of 307
building tree 88 of 307
building tree 89 of 307
building tree 90 of 307
building tree 91 of 307
building tree 92 of 307
building tree 93 of 307
building tree 94 of 307
building tree 95 of 307
building tree 96 of 307
building tree 97 of 307
building tree 98 of 307
building tree 99 of 307
building tree 100 of 307
building tree 101 of 307
building tree 102 of 307
building tree 103 of 307
building tree 104 of 307
building tree 105 of 307
building tree 106 of 307
building tree 107 of 307
building tree 108 of 307
building tree 109 of 307
building tree 110 of 307
building tree 111 of 307
building tree 112 of 307
building tree 113 of 307
building tree 114 of 307
building tree 115 of 307
building tree 116 of 307
building tree 117 of 307
building tree 118 of 307
building tree 119 of 307
building tree 120 of 307
building tree 121 of 307
building tree 122 of 307
building tree 123 of 307
building tree 124 of 307
building tree 125 of 307
building tree 126 of 307
building tree 127 of 307
building tree 128 of 307
building tree 129 of 307
building tree 130 of 307
building tree 131 of 307
building tree 132 of 307
building tree 133 of 307
building tree 134 of 307
building tree 135 of 307
building tree 136 of 307
building tree 137 of 307
building tree 138 of 307
building tree 139 of 307
building tree 140 of 307
building tree 141 of 307
building tree 142 of 307
building tree 143 of 307
building tree 144 of 307
building tree 145 of 307
building tree 146 of 307
building tree 147 of 307
building tree 148 of 307
building tree 149 of 307
building tree 150 of 307
building tree 151 of 307
building tree 152 of 307
building tree 153 of 307
building tree 154 of 307
building tree 155 of 307
building tree 156 of 307
building tree 157 of 307
building tree 158 of 307
building tree 159 of 307
building tree 160 of 307
building tree 161 of 307
building tree 162 of 307
building tree 163 of 307
building tree 164 of 307
building tree 165 of 307
building tree 166 of 307
building tree 167 of 307
building tree 168 of 307
building tree 169 of 307
building tree 170 of 307
building tree 171 of 307
building tree 172 of 307
building tree 173 of 307
building tree 174 of 307
building tree 175 of 307
building tree 176 of 307
building tree 177 of 307
building tree 178 of 307
building tree 179 of 307
building tree 180 of 307
building tree 181 of 307
building tree 182 of 307
building tree 183 of 307
building tree 184 of 307
building tree 185 of 307
building tree 186 of 307
building tree 187 of 307
building tree 188 of 307
building tree 189 of 307
building tree 190 of 307
building tree 191 of 307
building tree 192 of 307
building tree 193 of 307
building tree 194 of 307
building tree 195 of 307
building tree 196 of 307
building tree 197 of 307
building tree 198 of 307
building tree 199 of 307
building tree 200 of 307
building tree 201 of 307
building tree 202 of 307
building tree 203 of 307
building tree 204 of 307
building tree 205 of 307
building tree 206 of 307
building tree 207 of 307
building tree 208 of 307
building tree 209 of 307
building tree 210 of 307
building tree 211 of 307
building tree 212 of 307
building tree 213 of 307
building tree 214 of 307
building tree 215 of 307
building tree 216 of 307
building tree 217 of 307
building tree 218 of 307
building tree 219 of 307
building tree 220 of 307
building tree 221 of 307
building tree 222 of 307
building tree 223 of 307
building tree 224 of 307
building tree 225 of 307
building tree 226 of 307
building tree 227 of 307
building tree 228 of 307
building tree 229 of 307
building tree 230 of 307
building tree 231 of 307
building tree 232 of 307
building tree 233 of 307
building tree 234 of 307
building tree 235 of 307
building tree 236 of 307
building tree 237 of 307
building tree 238 of 307
building tree 239 of 307
building tree 240 of 307
building tree 241 of 307
building tree 242 of 307
building tree 243 of 307
building tree 244 of 307
building tree 245 of 307
building tree 246 of 307
building tree 247 of 307
building tree 248 of 307
building tree 249 of 307
building tree 250 of 307
building tree 251 of 307
building tree 252 of 307
building tree 253 of 307
building tree 254 of 307
building tree 255 of 307
building tree 256 of 307
building tree 257 of 307
building tree 258 of 307
building tree 259 of 307
building tree 260 of 307
building tree 261 of 307
building tree 262 of 307
building tree 263 of 307
building tree 264 of 307
building tree 265 of 307
building tree 266 of 307
building tree 267 of 307
building tree 268 of 307
building tree 269 of 307
building tree 270 of 307
building tree 271 of 307
building tree 272 of 307
building tree 273 of 307
building tree 274 of 307
building tree 275 of 307
building tree 276 of 307
building tree 277 of 307
building tree 278 of 307
building tree 279 of 307
building tree 280 of 307
building tree 281 of 307
building tree 282 of 307
building tree 283 of 307
building tree 284 of 307
building tree 285 of 307
building tree 286 of 307
building tree 287 of 307
building tree 288 of 307
building tree 289 of 307
building tree 290 of 307
building tree 291 of 307
building tree 292 of 307
building tree 293 of 307
building tree 294 of 307
building tree 295 of 307
building tree 296 of 307
building tree 297 of 307
building tree 298 of 307
building tree 299 of 307
building tree 300 of 307
building tree 301 of 307
building tree 302 of 307
building tree 303 of 307
building tree 304 of 307
building tree 305 of 307
building tree 306 of 307
building tree 307 of 307

[Parallel(n_jobs=1)]: Done 307 out of 307 | elapsed:    0.4s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 307 out of 307 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s

building tree 1 of 307
building tree 2 of 307
building tree 3 of 307
building tree 4 of 307
building tree 5 of 307
building tree 6 of 307
building tree 7 of 307
building tree 8 of 307
building tree 9 of 307
building tree 10 of 307
building tree 11 of 307
building tree 12 of 307
building tree 13 of 307
building tree 14 of 307
building tree 15 of 307
building tree 16 of 307
building tree 17 of 307
building tree 18 of 307
building tree 19 of 307
building tree 20 of 307
building tree 21 of 307
building tree 22 of 307
building tree 23 of 307
building tree 24 of 307
building tree 25 of 307
building tree 26 of 307
building tree 27 of 307
building tree 28 of 307
building tree 29 of 307
building tree 30 of 307
building tree 31 of 307
building tree 32 of 307
building tree 33 of 307
building tree 34 of 307
building tree 35 of 307
building tree 36 of 307
building tree 37 of 307
building tree 38 of 307
building tree 39 of 307
building tree 40 of 307
building tree 41 of 307
building tree 42 of 307
building tree 43 of 307
building tree 44 of 307
building tree 45 of 307
building tree 46 of 307
building tree 47 of 307
building tree 48 of 307
building tree 49 of 307
building tree 50 of 307
building tree 51 of 307
building tree 52 of 307
building tree 53 of 307
building tree 54 of 307
building tree 55 of 307
building tree 56 of 307
building tree 57 of 307
building tree 58 of 307
building tree 59 of 307
building tree 60 of 307
building tree 61 of 307
building tree 62 of 307
building tree 63 of 307
building tree 64 of 307
building tree 65 of 307
building tree 66 of 307
building tree 67 of 307
building tree 68 of 307
building tree 69 of 307
building tree 70 of 307
building tree 71 of 307
building tree 72 of 307
building tree 73 of 307
building tree 74 of 307
building tree 75 of 307
building tree 76 of 307
building tree 77 of 307
building tree 78 of 307
building tree 79 of 307
building tree 80 of 307
building tree 81 of 307
building tree 82 of 307
building tree 83 of 307
building tree 84 of 307
building tree 85 of 307
building tree 86 of 307
building tree 87 of 307
building tree 88 of 307
building tree 89 of 307
building tree 90 of 307
building tree 91 of 307
building tree 92 of 307
building tree 93 of 307
building tree 94 of 307
building tree 95 of 307
building tree 96 of 307
building tree 97 of 307
building tree 98 of 307
building tree 99 of 307
building tree 100 of 307
building tree 101 of 307
building tree 102 of 307
building tree 103 of 307
building tree 104 of 307
building tree 105 of 307
building tree 106 of 307
building tree 107 of 307
building tree 108 of 307
building tree 109 of 307
building tree 110 of 307
building tree 111 of 307
building tree 112 of 307
building tree 113 of 307
building tree 114 of 307
building tree 115 of 307
building tree 116 of 307
building tree 117 of 307
building tree 118 of 307
building tree 119 of 307
building tree 120 of 307
building tree 121 of 307
building tree 122 of 307
building tree 123 of 307
building tree 124 of 307
building tree 125 of 307
building tree 126 of 307
building tree 127 of 307
building tree 128 of 307
building tree 129 of 307
building tree 130 of 307
building tree 131 of 307
building tree 132 of 307
building tree 133 of 307
building tree 134 of 307
building tree 135 of 307
building tree 136 of 307
building tree 137 of 307
building tree 138 of 307
building tree 139 of 307
building tree 140 of 307
building tree 141 of 307
building tree 142 of 307
building tree 143 of 307
building tree 144 of 307
building tree 145 of 307
building tree 146 of 307
building tree 147 of 307
building tree 148 of 307
building tree 149 of 307
building tree 150 of 307
building tree 151 of 307
building tree 152 of 307
building tree 153 of 307
building tree 154 of 307
building tree 155 of 307
building tree 156 of 307
building tree 157 of 307
building tree 158 of 307
building tree 159 of 307
building tree 160 of 307
building tree 161 of 307
building tree 162 of 307
building tree 163 of 307
building tree 164 of 307
building tree 165 of 307
building tree 166 of 307
building tree 167 of 307
building tree 168 of 307
building tree 169 of 307
building tree 170 of 307
building tree 171 of 307
building tree 172 of 307
building tree 173 of 307
building tree 174 of 307
building tree 175 of 307
building tree 176 of 307
building tree 177 of 307
building tree 178 of 307
building tree 179 of 307
building tree 180 of 307
building tree 181 of 307
building tree 182 of 307
building tree 183 of 307
building tree 184 of 307
building tree 185 of 307
building tree 186 of 307
building tree 187 of 307
building tree 188 of 307
building tree 189 of 307
building tree 190 of 307
building tree 191 of 307
building tree 192 of 307
building tree 193 of 307
building tree 194 of 307
building tree 195 of 307
building tree 196 of 307
building tree 197 of 307
building tree 198 of 307
building tree 199 of 307
building tree 200 of 307
building tree 201 of 307
building tree 202 of 307
building tree 203 of 307
building tree 204 of 307
building tree 205 of 307
building tree 206 of 307
building tree 207 of 307
building tree 208 of 307
building tree 209 of 307
building tree 210 of 307
building tree 211 of 307
building tree 212 of 307
building tree 213 of 307
building tree 214 of 307
building tree 215 of 307
building tree 216 of 307
building tree 217 of 307
building tree 218 of 307
building tree 219 of 307
building tree 220 of 307
building tree 221 of 307
building tree 222 of 307
building tree 223 of 307
building tree 224 of 307
building tree 225 of 307
building tree 226 of 307
building tree 227 of 307
building tree 228 of 307
building tree 229 of 307
building tree 230 of 307
building tree 231 of 307
building tree 232 of 307
building tree 233 of 307
building tree 234 of 307
building tree 235 of 307
building tree 236 of 307
building tree 237 of 307
building tree 238 of 307
building tree 239 of 307
building tree 240 of 307
building tree 241 of 307
building tree 242 of 307
building tree 243 of 307
building tree 244 of 307
building tree 245 of 307
building tree 246 of 307
building tree 247 of 307
building tree 248 of 307
building tree 249 of 307
building tree 250 of 307
building tree 251 of 307
building tree 252 of 307
building tree 253 of 307
building tree 254 of 307
building tree 255 of 307
building tree 256 of 307
building tree 257 of 307
building tree 258 of 307
building tree 259 of 307
building tree 260 of 307
building tree 261 of 307
building tree 262 of 307
building tree 263 of 307
building tree 264 of 307
building tree 265 of 307
building tree 266 of 307
building tree 267 of 307
building tree 268 of 307
building tree 269 of 307
building tree 270 of 307
building tree 271 of 307
building tree 272 of 307
building tree 273 of 307
building tree 274 of 307
building tree 275 of 307
building tree 276 of 307
building tree 277 of 307
building tree 278 of 307
building tree 279 of 307
building tree 280 of 307
building tree 281 of 307
building tree 282 of 307
building tree 283 of 307
building tree 284 of 307
building tree 285 of 307
building tree 286 of 307
building tree 287 of 307
building tree 288 of 307
building tree 289 of 307
building tree 290 of 307
building tree 291 of 307
building tree 292 of 307
building tree 293 of 307
building tree 294 of 307
building tree 295 of 307
building tree 296 of 307
building tree 297 of 307
building tree 298 of 307
building tree 299 of 307
building tree 300 of 307
building tree 301 of 307
building tree 302 of 307
building tree 303 of 307
building tree 304 of 307
building tree 305 of 307
building tree 306 of 307
building tree 307 of 307

[Parallel(n_jobs=1)]: Done 307 out of 307 | elapsed:    0.3s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 307 out of 307 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s

building tree 1 of 307
building tree 2 of 307
building tree 3 of 307
building tree 4 of 307
building tree 5 of 307
building tree 6 of 307
building tree 7 of 307
building tree 8 of 307
building tree 9 of 307
building tree 10 of 307
building tree 11 of 307
building tree 12 of 307
building tree 13 of 307
building tree 14 of 307
building tree 15 of 307
building tree 16 of 307
building tree 17 of 307
building tree 18 of 307
building tree 19 of 307
building tree 20 of 307
building tree 21 of 307
building tree 22 of 307
building tree 23 of 307
building tree 24 of 307
building tree 25 of 307
building tree 26 of 307
building tree 27 of 307
building tree 28 of 307
building tree 29 of 307
building tree 30 of 307
building tree 31 of 307
building tree 32 of 307
building tree 33 of 307
building tree 34 of 307
building tree 35 of 307
building tree 36 of 307
building tree 37 of 307
building tree 38 of 307
building tree 39 of 307
building tree 40 of 307
building tree 41 of 307
building tree 42 of 307
building tree 43 of 307
building tree 44 of 307
building tree 45 of 307
building tree 46 of 307
building tree 47 of 307
building tree 48 of 307
building tree 49 of 307
building tree 50 of 307
building tree 51 of 307
building tree 52 of 307
building tree 53 of 307
building tree 54 of 307
building tree 55 of 307
building tree 56 of 307
building tree 57 of 307
building tree 58 of 307
building tree 59 of 307
building tree 60 of 307
building tree 61 of 307
building tree 62 of 307
building tree 63 of 307
building tree 64 of 307
building tree 65 of 307
building tree 66 of 307
building tree 67 of 307
building tree 68 of 307
building tree 69 of 307
building tree 70 of 307
building tree 71 of 307
building tree 72 of 307
building tree 73 of 307
building tree 74 of 307
building tree 75 of 307
building tree 76 of 307
building tree 77 of 307
building tree 78 of 307
building tree 79 of 307
building tree 80 of 307
building tree 81 of 307
building tree 82 of 307
building tree 83 of 307
building tree 84 of 307
building tree 85 of 307
building tree 86 of 307
building tree 87 of 307
building tree 88 of 307
building tree 89 of 307
building tree 90 of 307
building tree 91 of 307
building tree 92 of 307
building tree 93 of 307
building tree 94 of 307
building tree 95 of 307
building tree 96 of 307
building tree 97 of 307
building tree 98 of 307
building tree 99 of 307
building tree 100 of 307
building tree 101 of 307
building tree 102 of 307
building tree 103 of 307
building tree 104 of 307
building tree 105 of 307
building tree 106 of 307
building tree 107 of 307
building tree 108 of 307
building tree 109 of 307
building tree 110 of 307
building tree 111 of 307
building tree 112 of 307
building tree 113 of 307
building tree 114 of 307
building tree 115 of 307
building tree 116 of 307
building tree 117 of 307
building tree 118 of 307
building tree 119 of 307
building tree 120 of 307
building tree 121 of 307
building tree 122 of 307
building tree 123 of 307
building tree 124 of 307
building tree 125 of 307
building tree 126 of 307
building tree 127 of 307
building tree 128 of 307
building tree 129 of 307
building tree 130 of 307
building tree 131 of 307
building tree 132 of 307
building tree 133 of 307
building tree 134 of 307
building tree 135 of 307
building tree 136 of 307
building tree 137 of 307
building tree 138 of 307
building tree 139 of 307
building tree 140 of 307
building tree 141 of 307
building tree 142 of 307
building tree 143 of 307
building tree 144 of 307
building tree 145 of 307
building tree 146 of 307
building tree 147 of 307
building tree 148 of 307
building tree 149 of 307
building tree 150 of 307
building tree 151 of 307
building tree 152 of 307
building tree 153 of 307
building tree 154 of 307
building tree 155 of 307
building tree 156 of 307
building tree 157 of 307
building tree 158 of 307
building tree 159 of 307
building tree 160 of 307
building tree 161 of 307
building tree 162 of 307
building tree 163 of 307
building tree 164 of 307
building tree 165 of 307
building tree 166 of 307
building tree 167 of 307
building tree 168 of 307
building tree 169 of 307
building tree 170 of 307
building tree 171 of 307
building tree 172 of 307
building tree 173 of 307
building tree 174 of 307
building tree 175 of 307
building tree 176 of 307
building tree 177 of 307
building tree 178 of 307
building tree 179 of 307
building tree 180 of 307
building tree 181 of 307
building tree 182 of 307
building tree 183 of 307
building tree 184 of 307
building tree 185 of 307
building tree 186 of 307
building tree 187 of 307
building tree 188 of 307
building tree 189 of 307
building tree 190 of 307
building tree 191 of 307
building tree 192 of 307
building tree 193 of 307
building tree 194 of 307
building tree 195 of 307
building tree 196 of 307
building tree 197 of 307
building tree 198 of 307
building tree 199 of 307
building tree 200 of 307
building tree 201 of 307
building tree 202 of 307
building tree 203 of 307
building tree 204 of 307
building tree 205 of 307
building tree 206 of 307
building tree 207 of 307
building tree 208 of 307
building tree 209 of 307
building tree 210 of 307
building tree 211 of 307
building tree 212 of 307
building tree 213 of 307
building tree 214 of 307
building tree 215 of 307
building tree 216 of 307
building tree 217 of 307
building tree 218 of 307
building tree 219 of 307
building tree 220 of 307
building tree 221 of 307
building tree 222 of 307
building tree 223 of 307
building tree 224 of 307
building tree 225 of 307
building tree 226 of 307
building tree 227 of 307
building tree 228 of 307
building tree 229 of 307
building tree 230 of 307
building tree 231 of 307
building tree 232 of 307
building tree 233 of 307
building tree 234 of 307
building tree 235 of 307
building tree 236 of 307
building tree 237 of 307
building tree 238 of 307
building tree 239 of 307
building tree 240 of 307
building tree 241 of 307
building tree 242 of 307
building tree 243 of 307
building tree 244 of 307
building tree 245 of 307
building tree 246 of 307
building tree 247 of 307
building tree 248 of 307
building tree 249 of 307
building tree 250 of 307
building tree 251 of 307
building tree 252 of 307
building tree 253 of 307
building tree 254 of 307
building tree 255 of 307
building tree 256 of 307
building tree 257 of 307
building tree 258 of 307
building tree 259 of 307
building tree 260 of 307
building tree 261 of 307
building tree 262 of 307
building tree 263 of 307
building tree 264 of 307
building tree 265 of 307
building tree 266 of 307
building tree 267 of 307
building tree 268 of 307
building tree 269 of 307
building tree 270 of 307
building tree 271 of 307
building tree 272 of 307
building tree 273 of 307
building tree 274 of 307
building tree 275 of 307
building tree 276 of 307
building tree 277 of 307
building tree 278 of 307
building tree 279 of 307
building tree 280 of 307
building tree 281 of 307
building tree 282 of 307
building tree 283 of 307
building tree 284 of 307
building tree 285 of 307
building tree 286 of 307
building tree 287 of 307
building tree 288 of 307
building tree 289 of 307
building tree 290 of 307
building tree 291 of 307
building tree 292 of 307
building tree 293 of 307
building tree 294 of 307
building tree 295 of 307
building tree 296 of 307
building tree 297 of 307
building tree 298 of 307
building tree 299 of 307
building tree 300 of 307
building tree 301 of 307
building tree 302 of 307
building tree 303 of 307
building tree 304 of 307
building tree 305 of 307
building tree 306 of 307
building tree 307 of 307
Mean_RF_Acc :  0.5872519509476032

[Parallel(n_jobs=1)]: Done 307 out of 307 | elapsed:    0.3s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 307 out of 307 | elapsed:    0.0s finished

In [64]:
#from sklearn.tree import export_graphviz
#import pydot
# Pull out one tree from the forest
#tree = rf1.estimators_[5]
# Import tools needed for visualization
#from sklearn.tree import export_graphviz
#import pydot
# Pull out one tree from the forest
#tree = rf1.estimators_[5]
# Export the image to a dot file
#export_graphviz(tree, out_file = 'tree.dot', feature_names =None, rounded = True, precision = 1)
# Use dot file to create a graph
#(graph, ) = pydot.graph_from_dot_file('tree.dot')
# Write graph to a png file
#ygraph.write_png('tree.png')

In [65]:
#rf1.estimators_[5]

In [66]:
feature_list = list(sampl.columns)
importances = list(rf1.feature_importances_)
# List of tuples with variable and importance
feature_importances = [(feature, round(importance, 2)) for feature, importance in zip(feature_list, importances)]
# Sort the feature importances by most important first
feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)
# Print out the feature and importances 
[print('Variable: {:30} Importance: {}'.format(*pair)) for pair in feature_importances];

Variable: Team_1_RR                      Importance: 0.07
Variable: Team_1_KKR                     Importance: 0.06
Variable: Team_1_KXIP                    Importance: 0.06
Variable: Team_1_SRH                     Importance: 0.05
Variable: Team_2_CSK                     Importance: 0.05
Variable: Team_2_DC                      Importance: 0.05
Variable: Team_2_MI                      Importance: 0.05
Variable: Team_2_RCB                     Importance: 0.05
Variable: Team_2_RR                      Importance: 0.05
Variable: winner                         Importance: 0.04
Variable: Team_1_CSK                     Importance: 0.04
Variable: Team_1_DC                      Importance: 0.04
Variable: Team_1_MI                      Importance: 0.04
Variable: Team_1_RCB                     Importance: 0.04
Variable: Team_2_KKR                     Importance: 0.04
Variable: Team_2_KXIP                    Importance: 0.03
Variable: Team_2_SRH                     Importance: 0.03
Variable: toss_won_DC                    Importance: 0.03
Variable: toss_won_MI                    Importance: 0.03
Variable: toss_won_RCB                   Importance: 0.03
Variable: toss_won_SRH                   Importance: 0.03
Variable: toss_won_CSK                   Importance: 0.02
Variable: toss_won_KKR                   Importance: 0.02
Variable: toss_won_KXIP                  Importance: 0.02
Variable: toss_won_RR                    Importance: 0.02
Variable: toss_dec_bat                   Importance: 0.02

In [67]:
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
print(random_grid)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt'], 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None], 'min_samples_split': [2, 5, 10], 'min_samples_leaf': [1, 2, 4], 'bootstrap': [True, False]}

In [84]:
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rff = RandomForestClassifier()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rff, param_distributions = random_grid,
                               n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)
# Fit the random search mode
rf_random.fit(X_train, y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    9.6s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:   45.5s
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  1.7min finished
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning:

The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.

RandomizedSearchCV(cv=3, error_score='raise-deprecating',
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
                                                    n_estimators='warn',
                                                    n_jobs=None,
                                                    oob_sc...
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [10, 20, 30, 40, 50, 60,
                                                      70, 80, 90, 100, 110,
                                                      None],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   pre_dispatch='2*n_jobs', random_state=42, refit=True,
                   return_train_score=False, scoring=None, verbose=2)

In [85]:
rf_random.best_params_

{'n_estimators': 800,
 'min_samples_split': 10,
 'min_samples_leaf': 4,
 'max_features': 'sqrt',
 'max_depth': 50,
 'bootstrap': True}

In [86]:
score3 = rf_random.score(X_train, y_train)
score4 = rf_random.score(X_test, y_test)
print(score3)
print(score4)

0.6219512195121951
0.5725806451612904

In [87]:
preds=rf_random.predict(copyy)
print(preds)

['RR' 'DC' 'RCB' 'SRH' 'MI' 'DC' 'SRH' 'CSK' 'MI' 'KXIP' 'DC' 'MI' 'KKR'
 'KXIP' 'MI' 'SRH' 'CSK' 'RR' 'RCB' 'MI']

In [100]:
b=('1',2,'3',4)
type(b)
#print(b)

tuple

In [71]:
#copyy

In [72]:
#score = rf.score(X_train, y_train)
#score2 = rf.score(X_test, y_test)
#print(score)
#print(score2)

In [73]:
from sklearn.model_selection import GridSearchCV
# Create the parameter grid based on the results of random search 
param_grid = {
    'bootstrap': [True],
    'max_depth': [80, 90, 100, 110],
    'max_features': [2, 3],
    'min_samples_leaf': [3, 4, 5],
    'min_samples_split': [8, 10, 12],
    'n_estimators': [100, 200, 300, 1000]
}
# Create a based model
rfff = RandomForestClassifier()
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rfff, param_grid = param_grid, cv = 3, n_jobs = -1, verbose = 2)
grid_search.fit(X_train, y_train)

Fitting 3 folds for each of 288 candidates, totalling 864 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    2.7s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:   16.6s
[Parallel(n_jobs=-1)]: Done 349 tasks      | elapsed:   43.5s
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-1)]: Done 864 out of 864 | elapsed:  1.6min finished
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning:

The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.

GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False),
             iid='warn', n_jobs=-1,
             param_grid={'bootstrap': [True], 'max_depth': [80, 90, 100, 110],
                         'max_features': [2, 3], 'min_samples_leaf': [3, 4, 5],
                         'min_samples_split': [8, 10, 12],
                         'n_estimators': [100, 200, 300, 1000]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=2)

In [74]:
grid_search.best_params_

{'bootstrap': True,
 'max_depth': 110,
 'max_features': 3,
 'min_samples_leaf': 5,
 'min_samples_split': 12,
 'n_estimators': 200}

In [75]:
score5 = grid_search.score(X_train, y_train)
score6 = grid_search.score(X_test, y_test)
print(score)
print(score2)

0.6864754098360656
0.6097560975609756

In [76]:
predis=grid_search.predict(copyy)
print(predis)

['CSK' 'DC' 'RCB' 'SRH' 'MI' 'DC' 'SRH' 'CSK' 'RR' 'KKR' 'DC' 'MI' 'KKR'
 'KXIP' 'MI' 'RCB' 'CSK' 'RR' 'RCB' 'MI']

In [1329]:
pd.set_option('display.max_columns', None)

In [1351]:
sample123=old_matches.drop(['id','city','season','date','result','dl_applied','win_by_runs','win_by_wickets','player_of_match','umpire1','umpire2','umpire3'],axis=1)
sample123

,team1,team2,toss_winner,toss_decision,winner,venue
0,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
1,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,Maharashtra Cricket Association Stadium
2,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,Saurashtra Cricket Association Stadium
3,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,Holkar Cricket Stadium
4,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,M Chinnaswamy Stadium
...,...,...,...,...,...,...
778,Rajasthan Royals,Delhi Capitals,Rajasthan Royals,field,Delhi Capitals,Sharjah Cricket Stadium
779,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,bat,Kolkata Knight Riders,Sheikh Zayed Stadium
780,Chennai Super Kings,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,Dubai International Cricket Stadium
781,Sunrisers Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,bat,Rajasthan Royals,Dubai International Cricket Stadium
782,Mumbai Indians,Delhi Capitals,Delhi Capitals,bat,Mumbai Indians,Sheikh Zayed Stadium

In [1352]:
sample3=sample123[(sample123['venue']=='Sheikh Zayed Stadium')| (sample123['venue']=='Sharjah Cricket Stadium')| (sample123['venue']=='Dubai International Cricket Stadium')]
sample3

,team1,team2,toss_winner,toss_decision,winner,venue
457,Kolkata Knight Riders,Mumbai Indians,Kolkata Knight Riders,bat,Kolkata Knight Riders,Sheikh Zayed Stadium
458,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore,Sharjah Cricket Stadium
459,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,bat,Kings XI Punjab,Sheikh Zayed Stadium
460,Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,Sheikh Zayed Stadium
461,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore,Dubai International Cricket Stadium
462,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders,bat,Delhi Daredevils,Dubai International Cricket Stadium
463,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,Sharjah Cricket Stadium
464,Chennai Super Kings,Delhi Daredevils,Chennai Super Kings,bat,Chennai Super Kings,Sheikh Zayed Stadium
465,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Kings XI Punjab,Sharjah Cricket Stadium
466,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,field,Chennai Super Kings,Dubai International Cricket Stadium
467,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,Sharjah Cricket Stadium
468,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,Dubai International Cricket Stadium
469,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,Chennai Super Kings,Dubai International Cricket Stadium
470,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,Sheikh Zayed Stadium
471,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,Kings XI Punjab,Sheikh Zayed Stadium
472,Mumbai Indians,Delhi Daredevils,Mumbai Indians,bat,Delhi Daredevils,Sharjah Cricket Stadium
473,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad,bat,Chennai Super Kings,Sharjah Cricket Stadium
474,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,Dubai International Cricket Stadium
475,Rajasthan Royals,Kolkata Knight Riders,Rajasthan Royals,bat,Rajasthan Royals,Sheikh Zayed Stadium
476,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Sunrisers Hyderabad,Dubai International Cricket Stadium
756,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,Sheikh Zayed Stadium
757,Delhi Capitals,Kings XI Punjab,Kings XI Punjab,field,Delhi Capitals,Dubai International Cricket Stadium
758,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,field,Royal Challengers Bangalore,Dubai International Cricket Stadium
759,Rajasthan Royals,Chennai Super Kings,Chennai Super Kings,field,Rajasthan Royals,Sharjah Cricket Stadium
760,Kolkata Knight Riders,Mumbai Indians,Kolkata Knight Riders,field,Mumbai Indians,Sheikh Zayed Stadium
761,Kings XI Punjab,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Kings XI Punjab,Dubai International Cricket Stadium
762,Chennai Super Kings,Delhi Capitals,Chennai Super Kings,field,Delhi Capitals,Dubai International Cricket Stadium
763,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,Sheikh Zayed Stadium
764,Kings XI Punjab,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,Sharjah Cricket Stadium
765,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,Dubai International Cricket Stadium
766,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,field,Sunrisers Hyderabad,Sheikh Zayed Stadium
767,Rajasthan Royals,Kolkata Knight Riders,Rajasthan Royals,field,Kolkata Knight Riders,Dubai International Cricket Stadium
768,Kings XI Punjab,Mumbai Indians,Kings XI Punjab,field,Mumbai Indians,Sheikh Zayed Stadium
769,Chennai Super Kings,Sunrisers Hyderabad,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,Dubai International Cricket Stadium
770,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,bat,Royal Challengers Bangalore,Sheikh Zayed Stadium
771,Delhi Capitals,Kolkata Knight Riders,Kolkata Knight Riders,field,Delhi Capitals,Sharjah Cricket Stadium
772,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,Mumbai Indians,Sharjah Cricket Stadium
773,Kings XI Punjab,Chennai Super Kings,Kings XI Punjab,bat,Chennai Super Kings,Dubai International Cricket Stadium
774,Royal Challengers Bangalore,Delhi Capitals,Royal Challengers Bangalore,field,Delhi Capitals,Dubai International Cricket Stadium
775,Mumbai Indians,Rajasthan Royals,Mumbai Indians,bat,Mumbai Indians,Sheikh Zayed Stadium
776,Kolkata Knight Riders,Chennai Super Kings,Kolkata Knight Riders,bat,Kolkata Knight Riders,Sheikh Zayed Stadium
777,Sunrisers Hyderabad,Kings XI Punjab,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,Dubai International Cricket Stadium
778,Rajasthan Royals,Delhi Capitals,Rajasthan Royals,field,Delhi Capitals,Sharjah Cricket Stadium
779,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,bat,Kolkata Knight Riders,Sheikh Zayed Stadium
780,Chennai Super Kings,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,Dubai International Cricket Stadium
781,Sunrisers Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,bat,Rajasthan Royals,Dubai International Cricket Stadium
782,Mumbai Indians,Delhi Capitals,Delhi Capitals,bat,Mumbai Indians,Sheikh Zayed Stadium

In [1353]:
len(sample3)

47

In [1354]:
# or (sample123['venue']=='Sharjah Cricket Stadium')

In [1355]:
#or (sample123['venue']=='Dubai International Cricket Stadium')

In [1356]:
x=['Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
    'Rising Pune Supergiant', 'Royal Challengers Bangalore',
    'Kolkata Knight Riders', 'Delhi Daredevils', 'Kings XI Punjab',
    'Chennai Super Kings', 'Rajasthan Royals', 'Deccan Chargers',
    'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants', 'Delhi Capitals','Sheikh Zayed Stadium','Dubai International Cricket Stadium','Sharjah Cricket Stadium']
#y = [1,2,3,4,5,6,7,8,9,10,11,12,13,4,14]
y = ['SRH','MI','GL','RPS','RCB','KKR','DC','KXIP','CSK','RR','SRH','KTK','PW','RPS','DC','SKZ','dubai','Sharz']

sample3.replace(x,y,inplace = True)
sample3

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4263: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

    team1 team2 toss_winner toss_decision winner  venue
457   KKR    MI         KKR           bat    KKR    SKZ
458    DC   RCB         RCB         field    RCB  Sharz
459   CSK  KXIP         CSK           bat   KXIP    SKZ
460   SRH    RR          RR         field     RR    SKZ
461    MI   RCB         RCB         field    RCB  dubai
462   KKR    DC         KKR           bat     DC  dubai
463    RR  KXIP        KXIP         field   KXIP  Sharz
464   CSK    DC         CSK           bat    CSK    SKZ
465  KXIP   SRH         SRH         field   KXIP  Sharz
466   CSK    RR          RR         field    CSK  dubai
467   KKR   RCB         RCB         field    KKR  Sharz
468   SRH    DC         SRH           bat    SRH  dubai
469    MI   CSK          MI           bat    CSK  dubai
470   RCB    RR          RR         field     RR    SKZ
471  KXIP   KKR         KKR         field   KXIP    SKZ
472    MI    DC          MI           bat     DC  Sharz
473   SRH   CSK         SRH           bat    CSK  Sharz
474   RCB  KXIP        KXIP         field   KXIP  dubai
475    RR   KKR          RR           bat     RR    SKZ
476   SRH    MI          MI         field    SRH  dubai
756    MI   CSK         CSK         field    CSK    SKZ
757    DC  KXIP        KXIP         field     DC  dubai
758   SRH   RCB         SRH         field    RCB  dubai
759    RR   CSK         CSK         field     RR  Sharz
760   KKR    MI         KKR         field     MI    SKZ
761  KXIP   RCB         RCB         field   KXIP  dubai
762   CSK    DC         CSK         field     DC  dubai
763   SRH   KKR         SRH           bat    KKR    SKZ
764  KXIP    RR          RR         field     RR  Sharz
765   RCB    MI          MI         field    RCB  dubai
766    DC   SRH          DC         field    SRH    SKZ
767    RR   KKR          RR         field    KKR  dubai
768  KXIP    MI        KXIP         field     MI    SKZ
769   CSK   SRH         SRH           bat    SRH  dubai
770   RCB    RR          RR           bat    RCB    SKZ
771    DC   KKR         KKR         field     DC  Sharz
772    MI   SRH          MI           bat     MI  Sharz
773  KXIP   CSK        KXIP           bat    CSK  dubai
774   RCB    DC         RCB         field     DC  dubai
775    MI    RR          MI           bat     MI    SKZ
776   KKR   CSK         KKR           bat    KKR    SKZ
777   SRH  KXIP         SRH           bat    SRH  dubai
778    RR    DC          RR         field     DC  Sharz
779  KXIP   KKR         KKR           bat    KKR    SKZ
780   CSK   RCB         RCB           bat    RCB  dubai
781   SRH    RR         SRH           bat     RR  dubai
782    MI    DC          DC           bat     MI    SKZ

In [1357]:
sample3 = sample3[sample3.team1 != 'KTK']
sample3 = sample3[sample3.team1 != 'RPS']
sample3 = sample3[sample3.team1 != 'PW']
sample3 = sample3[sample3.team1 != 'GL']#KTK RPS PW GL
sample3

    team1 team2 toss_winner toss_decision winner  venue
457   KKR    MI         KKR           bat    KKR    SKZ
458    DC   RCB         RCB         field    RCB  Sharz
459   CSK  KXIP         CSK           bat   KXIP    SKZ
460   SRH    RR          RR         field     RR    SKZ
461    MI   RCB         RCB         field    RCB  dubai
462   KKR    DC         KKR           bat     DC  dubai
463    RR  KXIP        KXIP         field   KXIP  Sharz
464   CSK    DC         CSK           bat    CSK    SKZ
465  KXIP   SRH         SRH         field   KXIP  Sharz
466   CSK    RR          RR         field    CSK  dubai
467   KKR   RCB         RCB         field    KKR  Sharz
468   SRH    DC         SRH           bat    SRH  dubai
469    MI   CSK          MI           bat    CSK  dubai
470   RCB    RR          RR         field     RR    SKZ
471  KXIP   KKR         KKR         field   KXIP    SKZ
472    MI    DC          MI           bat     DC  Sharz
473   SRH   CSK         SRH           bat    CSK  Sharz
474   RCB  KXIP        KXIP         field   KXIP  dubai
475    RR   KKR          RR           bat     RR    SKZ
476   SRH    MI          MI         field    SRH  dubai
756    MI   CSK         CSK         field    CSK    SKZ
757    DC  KXIP        KXIP         field     DC  dubai
758   SRH   RCB         SRH         field    RCB  dubai
759    RR   CSK         CSK         field     RR  Sharz
760   KKR    MI         KKR         field     MI    SKZ
761  KXIP   RCB         RCB         field   KXIP  dubai
762   CSK    DC         CSK         field     DC  dubai
763   SRH   KKR         SRH           bat    KKR    SKZ
764  KXIP    RR          RR         field     RR  Sharz
765   RCB    MI          MI         field    RCB  dubai
766    DC   SRH          DC         field    SRH    SKZ
767    RR   KKR          RR         field    KKR  dubai
768  KXIP    MI        KXIP         field     MI    SKZ
769   CSK   SRH         SRH           bat    SRH  dubai
770   RCB    RR          RR           bat    RCB    SKZ
771    DC   KKR         KKR         field     DC  Sharz
772    MI   SRH          MI           bat     MI  Sharz
773  KXIP   CSK        KXIP           bat    CSK  dubai
774   RCB    DC         RCB         field     DC  dubai
775    MI    RR          MI           bat     MI    SKZ
776   KKR   CSK         KKR           bat    KKR    SKZ
777   SRH  KXIP         SRH           bat    SRH  dubai
778    RR    DC          RR         field     DC  Sharz
779  KXIP   KKR         KKR           bat    KKR    SKZ
780   CSK   RCB         RCB           bat    RCB  dubai
781   SRH    RR         SRH           bat     RR  dubai
782    MI    DC          DC           bat     MI    SKZ

In [1358]:
sample3=sample3.dropna()
sample3

    team1 team2 toss_winner toss_decision winner  venue
457   KKR    MI         KKR           bat    KKR    SKZ
458    DC   RCB         RCB         field    RCB  Sharz
459   CSK  KXIP         CSK           bat   KXIP    SKZ
460   SRH    RR          RR         field     RR    SKZ
461    MI   RCB         RCB         field    RCB  dubai
462   KKR    DC         KKR           bat     DC  dubai
463    RR  KXIP        KXIP         field   KXIP  Sharz
464   CSK    DC         CSK           bat    CSK    SKZ
465  KXIP   SRH         SRH         field   KXIP  Sharz
466   CSK    RR          RR         field    CSK  dubai
467   KKR   RCB         RCB         field    KKR  Sharz
468   SRH    DC         SRH           bat    SRH  dubai
469    MI   CSK          MI           bat    CSK  dubai
470   RCB    RR          RR         field     RR    SKZ
471  KXIP   KKR         KKR         field   KXIP    SKZ
472    MI    DC          MI           bat     DC  Sharz
473   SRH   CSK         SRH           bat    CSK  Sharz
474   RCB  KXIP        KXIP         field   KXIP  dubai
475    RR   KKR          RR           bat     RR    SKZ
476   SRH    MI          MI         field    SRH  dubai
756    MI   CSK         CSK         field    CSK    SKZ
757    DC  KXIP        KXIP         field     DC  dubai
758   SRH   RCB         SRH         field    RCB  dubai
759    RR   CSK         CSK         field     RR  Sharz
760   KKR    MI         KKR         field     MI    SKZ
761  KXIP   RCB         RCB         field   KXIP  dubai
762   CSK    DC         CSK         field     DC  dubai
763   SRH   KKR         SRH           bat    KKR    SKZ
764  KXIP    RR          RR         field     RR  Sharz
765   RCB    MI          MI         field    RCB  dubai
766    DC   SRH          DC         field    SRH    SKZ
767    RR   KKR          RR         field    KKR  dubai
768  KXIP    MI        KXIP         field     MI    SKZ
769   CSK   SRH         SRH           bat    SRH  dubai
770   RCB    RR          RR           bat    RCB    SKZ
771    DC   KKR         KKR         field     DC  Sharz
772    MI   SRH          MI           bat     MI  Sharz
773  KXIP   CSK        KXIP           bat    CSK  dubai
774   RCB    DC         RCB         field     DC  dubai
775    MI    RR          MI           bat     MI    SKZ
776   KKR   CSK         KKR           bat    KKR    SKZ
777   SRH  KXIP         SRH           bat    SRH  dubai
778    RR    DC          RR         field     DC  Sharz
779  KXIP   KKR         KKR           bat    KKR    SKZ
780   CSK   RCB         RCB           bat    RCB  dubai
781   SRH    RR         SRH           bat     RR  dubai
782    MI    DC          DC           bat     MI    SKZ

In [1359]:
sample3 = sample3[sample3.team2 != 'KTK']
sample3 = sample3[sample3.team2 != 'RPS']
sample3 = sample3[sample3.team2 != 'PW']
sample3 = sample3[sample3.team2 != 'GL']#KTK RPS PW GL
sample3

    team1 team2 toss_winner toss_decision winner  venue
457   KKR    MI         KKR           bat    KKR    SKZ
458    DC   RCB         RCB         field    RCB  Sharz
459   CSK  KXIP         CSK           bat   KXIP    SKZ
460   SRH    RR          RR         field     RR    SKZ
461    MI   RCB         RCB         field    RCB  dubai
462   KKR    DC         KKR           bat     DC  dubai
463    RR  KXIP        KXIP         field   KXIP  Sharz
464   CSK    DC         CSK           bat    CSK    SKZ
465  KXIP   SRH         SRH         field   KXIP  Sharz
466   CSK    RR          RR         field    CSK  dubai
467   KKR   RCB         RCB         field    KKR  Sharz
468   SRH    DC         SRH           bat    SRH  dubai
469    MI   CSK          MI           bat    CSK  dubai
470   RCB    RR          RR         field     RR    SKZ
471  KXIP   KKR         KKR         field   KXIP    SKZ
472    MI    DC          MI           bat     DC  Sharz
473   SRH   CSK         SRH           bat    CSK  Sharz
474   RCB  KXIP        KXIP         field   KXIP  dubai
475    RR   KKR          RR           bat     RR    SKZ
476   SRH    MI          MI         field    SRH  dubai
756    MI   CSK         CSK         field    CSK    SKZ
757    DC  KXIP        KXIP         field     DC  dubai
758   SRH   RCB         SRH         field    RCB  dubai
759    RR   CSK         CSK         field     RR  Sharz
760   KKR    MI         KKR         field     MI    SKZ
761  KXIP   RCB         RCB         field   KXIP  dubai
762   CSK    DC         CSK         field     DC  dubai
763   SRH   KKR         SRH           bat    KKR    SKZ
764  KXIP    RR          RR         field     RR  Sharz
765   RCB    MI          MI         field    RCB  dubai
766    DC   SRH          DC         field    SRH    SKZ
767    RR   KKR          RR         field    KKR  dubai
768  KXIP    MI        KXIP         field     MI    SKZ
769   CSK   SRH         SRH           bat    SRH  dubai
770   RCB    RR          RR           bat    RCB    SKZ
771    DC   KKR         KKR         field     DC  Sharz
772    MI   SRH          MI           bat     MI  Sharz
773  KXIP   CSK        KXIP           bat    CSK  dubai
774   RCB    DC         RCB         field     DC  dubai
775    MI    RR          MI           bat     MI    SKZ
776   KKR   CSK         KKR           bat    KKR    SKZ
777   SRH  KXIP         SRH           bat    SRH  dubai
778    RR    DC          RR         field     DC  Sharz
779  KXIP   KKR         KKR           bat    KKR    SKZ
780   CSK   RCB         RCB           bat    RCB  dubai
781   SRH    RR         SRH           bat     RR  dubai
782    MI    DC          DC           bat     MI    SKZ

In [1360]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [1361]:
sample3.dtypes

team1            object
team2            object
toss_winner      object
toss_decision    object
winner           object
venue            object
dtype: object

In [1362]:
sample3 = pd.get_dummies(sample3, prefix=['Team_1', 'Team_2','venue','toss_won','toss_dec'], columns=['team1', 'team2','venue','toss_winner','toss_decision'])
sample3

,winner,Team_1_CSK,Team_1_DC,Team_1_KKR,Team_1_KXIP,Team_1_MI,Team_1_RCB,Team_1_RR,Team_1_SRH,Team_2_CSK,Team_2_DC,Team_2_KKR,Team_2_KXIP,Team_2_MI,Team_2_RCB,Team_2_RR,Team_2_SRH,venue_SKZ,venue_Sharz,venue_dubai,toss_won_CSK,toss_won_DC,toss_won_KKR,toss_won_KXIP,toss_won_MI,toss_won_RCB,toss_won_RR,toss_won_SRH,toss_dec_bat,toss_dec_field
457,KKR,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0
458,RCB,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1
459,KXIP,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0
460,RR,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,1
461,RCB,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1
462,DC,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0
463,KXIP,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1
464,CSK,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0
465,KXIP,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,1
466,CSK,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1
467,KKR,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1
468,SRH,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0
469,CSK,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0
470,RR,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,1
471,KXIP,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1
472,DC,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0
473,CSK,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0
474,KXIP,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1
475,RR,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0
476,SRH,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1
756,CSK,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1
757,DC,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1
758,RCB,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1
759,RR,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1
760,MI,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1
761,KXIP,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1
762,DC,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1
763,KKR,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0
764,RR,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,1
765,RCB,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1
766,SRH,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,1
767,KKR,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1
768,MI,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1
769,SRH,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,1,0
770,RCB,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,1,0
771,DC,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1
772,MI,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,1,0
773,CSK,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0
774,DC,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1
775,MI,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0
776,KKR,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0
777,SRH,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0
778,DC,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1
779,KKR,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0
780,RCB,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0
781,RR,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,1,0
782,MI,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0

In [1363]:
X = sample3.drop(['winner'], axis=1)
y = sample3["winner"]

In [1364]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
X_train

,Team_1_CSK,Team_1_DC,Team_1_KKR,Team_1_KXIP,Team_1_MI,Team_1_RCB,Team_1_RR,Team_1_SRH,Team_2_CSK,Team_2_DC,Team_2_KKR,Team_2_KXIP,Team_2_MI,Team_2_RCB,Team_2_RR,Team_2_SRH,venue_SKZ,venue_Sharz,venue_dubai,toss_won_CSK,toss_won_DC,toss_won_KKR,toss_won_KXIP,toss_won_MI,toss_won_RCB,toss_won_RR,toss_won_SRH,toss_dec_bat,toss_dec_field
465,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,1
460,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,1
463,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1
776,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0
769,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,1,0
470,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,1
474,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1
780,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0
472,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0
466,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1
473,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0
765,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1
768,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1
781,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,1,0
457,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0
767,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1
766,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,1
462,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0
468,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0
770,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,1,0
458,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1
777,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0
757,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1
459,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0
771,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1
759,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1
773,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0
467,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1
758,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1
475,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0
782,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0
756,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1
464,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0
778,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1
471,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1
764,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,1
774,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1

In [1404]:
rf5 = RandomForestClassifier(n_estimators=20, max_depth=20,oob_score=True ,class_weight='balanced',verbose=2,n_jobs=-1,random_state=12)
rf5.fit(X_train, y_train)

building tree 1 of 20
building tree 2 of 20
building tree 3 of 20
building tree 4 of 20
building tree 5 of 20
building tree 6 of 20
building tree 7 of 20
building tree 8 of 20
building tree 9 of 20
building tree 10 of 20
building tree 11 of 20
building tree 12 of 20
building tree 13 of 20building tree 14 of 20
building tree 15 of 20

building tree 16 of 20
building tree 17 of 20
building tree 18 of 20
building tree 19 of 20building tree 20 of 20

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  16 out of  20 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done  20 out of  20 | elapsed:    0.0s finished

RandomForestClassifier(bootstrap=True, class_weight='balanced',
                       criterion='gini', max_depth=20, max_features='auto',
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=20, n_jobs=-1, oob_score=True,
                       random_state=12, verbose=2, warm_start=False)

In [1405]:
score = rf5.score(X_train, y_train)
score2 = rf5.score(X_test, y_test)
print(score)
print(score2)

[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  16 out of  20 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=8)]: Done  20 out of  20 | elapsed:    0.0s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  16 out of  20 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=8)]: Done  20 out of  20 | elapsed:    0.0s finished

0.972972972972973
0.3

In [1406]:
print(rf1.oob_score_)

0.5147058823529411

In [1407]:
copy4=pd.read_csv('2020 Copy4.csv')
copy4

,Team,Team2,toss_winner,toss_decision,venue
0,Royal challengers bangalore,Kolkata knight riders,RCB,bat,Sharjah
1,Sunrisers hyderabad,Chennai super kings,CSK,bat,Dubai
2,Delhi capitals,Rajasthan royals,RR,bat,Dubai
3,Royal challengers,Kings xi punjab,KXIP,bat,Sharjah
4,Mumbai indians,Kolkata knight riders,MI,bat,Abu dhabi
5,Rajasthan royals,Royal challengers bangalore,RR,bat,Dubai
6,Delhi capitals,Chennai super kings,CSK,bat,Sharjah
7,Sunrisers hyderabad,Kolkata knight riders,KKR,bat,Abu dhabi
8,Mumbai indians,Kings xi punjab,MI,bat,Dubai
9,Chennai super kings,Rajasthan royals,RR,bat,Abu dhabi
10,Kings xi punjab,Delhi capitals,DC,field,Dubai
11,Kolkata knight riders,Royal challengers bangalore,RCB,field,Abu dhabi
12,Rajasthan royals,Sunrisers hyderabad,SRH,field,Dubai
13,Chennai super kings,Mumbai indians,MI,field,Sharjah
14,Kolkata knight riders,Delhi capitals,DC,field,Abu dhabi
15,Kings xi punjab,Sunrisers hyderabad,KXIP,field,Dubai
16,Royal challengers bangalore,Chennai super kings,CSK,field,Dubai
17,Rajasthan royals,Mumbai indians,MI,field,Abu dhabi
18,Kolkata knight riders,Kings xi punjab,KKR,field,Sharjah
19,Sunrisers hyderabad,Delhi capitals,DC,field,Dubai
20,Mumbai indians,Royal challengers bangalore,MI,field,Abu dhabi
21,Chennai super kings,Kolkata knight riders,KKR,field,Dubai
22,Kings xi punjab,Rajasthan royals,KXIP,field,Abu dhabi
23,Delhi capitals,Mumbai indians,DC,field,Dubai
24,Royal challengers bangalore,Sunrisers hyderabad,SRH,field,Sharjah
25,Chennai super kings,Kings xi punjab,CSK,field,Abu dhabi
26,Kolkata knight riders,Rajasthan royals,KKR,field,Dubai
27,Delhi capitals,Royal challengers bangalore,RCB,field,Abu dhabi
28,Sunrisers hyderabad,Mumbai indians,MI,field,Sharjah

In [1408]:
x=['Sunrisers hyderabad', 'Mumbai indians', 'Gujarat Lions',
    'Rising Pune Supergiant', 'Royal challengers bangalore',
    'Kolkata knight riders', 'Delhi Daredevils', 'Kings xi punjab',
    'Chennai super kings', 'Rajasthan royals', 'Deccan Chargers',
    'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants', 'Delhi capitals','Abu dhabi','Dubai','Sharjah','Royal challengers']
#y = [1,2,3,4,5,6,7,8,9,10,11,12,13,4,14]
y = ['SRH','MI','GL','RPS','RCB','KKR','DC','KXIP','CSK','RR','SRH','KTK','PW','RPS','DC','SKZ','dubai','Sharz','RCB']

copy4.replace(x,y,inplace = True)
copy4

    Team Team2 toss_winner toss_decision  venue
0    RCB   KKR         RCB           bat  Sharz
1    SRH   CSK         CSK           bat  dubai
2     DC    RR          RR           bat  dubai
3    RCB  KXIP        KXIP           bat  Sharz
4     MI   KKR          MI           bat    SKZ
5     RR   RCB          RR           bat  dubai
6     DC   CSK         CSK           bat  Sharz
7    SRH   KKR         KKR           bat    SKZ
8     MI  KXIP          MI           bat  dubai
9    CSK    RR          RR           bat    SKZ
10  KXIP    DC          DC         field  dubai
11   KKR   RCB         RCB         field    SKZ
12    RR   SRH         SRH         field  dubai
13   CSK    MI          MI         field  Sharz
14   KKR    DC          DC         field    SKZ
15  KXIP   SRH        KXIP         field  dubai
16   RCB   CSK         CSK         field  dubai
17    RR    MI          MI         field    SKZ
18   KKR  KXIP         KKR         field  Sharz
19   SRH    DC          DC         field  dubai
20    MI   RCB          MI         field    SKZ
21   CSK   KKR         KKR         field  dubai
22  KXIP    RR        KXIP         field    SKZ
23    DC    MI          DC         field  dubai
24   RCB   SRH         SRH         field  Sharz
25   CSK  KXIP         CSK         field    SKZ
26   KKR    RR         KKR         field  dubai
27    DC   RCB         RCB         field    SKZ
28   SRH    MI          MI         field  Sharz

In [1409]:
sample3

,winner,Team_1_CSK,Team_1_DC,Team_1_KKR,Team_1_KXIP,Team_1_MI,Team_1_RCB,Team_1_RR,Team_1_SRH,Team_2_CSK,Team_2_DC,Team_2_KKR,Team_2_KXIP,Team_2_MI,Team_2_RCB,Team_2_RR,Team_2_SRH,venue_SKZ,venue_Sharz,venue_dubai,toss_won_CSK,toss_won_DC,toss_won_KKR,toss_won_KXIP,toss_won_MI,toss_won_RCB,toss_won_RR,toss_won_SRH,toss_dec_bat,toss_dec_field
457,KKR,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0
458,RCB,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1
459,KXIP,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0
460,RR,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,1
461,RCB,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1
462,DC,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0
463,KXIP,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1
464,CSK,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0
465,KXIP,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,1
466,CSK,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1
467,KKR,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1
468,SRH,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0
469,CSK,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0
470,RR,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,1
471,KXIP,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1
472,DC,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0
473,CSK,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0
474,KXIP,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1
475,RR,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0
476,SRH,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1
756,CSK,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1
757,DC,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1
758,RCB,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1
759,RR,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1
760,MI,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1
761,KXIP,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1
762,DC,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1
763,KKR,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0
764,RR,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,1
765,RCB,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1
766,SRH,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,1
767,KKR,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1
768,MI,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1
769,SRH,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,1,0
770,RCB,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,1,0
771,DC,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1
772,MI,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,1,0
773,CSK,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0
774,DC,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1
775,MI,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0
776,KKR,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0
777,SRH,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0
778,DC,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1
779,KKR,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0
780,RCB,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0
781,RR,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,1,0
782,MI,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0

In [1410]:
copycat = pd.get_dummies(copy4, prefix=['Team_1', 'Team_2','toss_won','toss_dec','venue'], columns=['Team', 'Team2','toss_winner','toss_decision','venue'])
copycat

,Team_1_CSK,Team_1_DC,Team_1_KKR,Team_1_KXIP,Team_1_MI,Team_1_RCB,Team_1_RR,Team_1_SRH,Team_2_CSK,Team_2_DC,Team_2_KKR,Team_2_KXIP,Team_2_MI,Team_2_RCB,Team_2_RR,Team_2_SRH,toss_won_CSK,toss_won_DC,toss_won_KKR,toss_won_KXIP,toss_won_MI,toss_won_RCB,toss_won_RR,toss_won_SRH,toss_dec_bat,toss_dec_field,venue_SKZ,venue_Sharz,venue_dubai
0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0
1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1
2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,1
3,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0
4,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0
5,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1
6,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0
7,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0
8,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1
9,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,0,0
10,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1
11,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0
12,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,1
13,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0
14,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0
15,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,1
16,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1
17,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0
18,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0
19,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1
20,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0
21,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1
22,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,1,0,0
23,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1
24,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,0
25,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0
26,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1
27,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0
28,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0

In [1411]:
copycat

,Team_1_CSK,Team_1_DC,Team_1_KKR,Team_1_KXIP,Team_1_MI,Team_1_RCB,Team_1_RR,Team_1_SRH,Team_2_CSK,Team_2_DC,Team_2_KKR,Team_2_KXIP,Team_2_MI,Team_2_RCB,Team_2_RR,Team_2_SRH,toss_won_CSK,toss_won_DC,toss_won_KKR,toss_won_KXIP,toss_won_MI,toss_won_RCB,toss_won_RR,toss_won_SRH,toss_dec_bat,toss_dec_field,venue_SKZ,venue_Sharz,venue_dubai
0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0
1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1
2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,1
3,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0
4,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0
5,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1
6,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0
7,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0
8,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1
9,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,0,0
10,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1
11,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0
12,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,1
13,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0
14,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0
15,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,1
16,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1
17,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0
18,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0
19,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1
20,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0
21,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1
22,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,1,0,0
23,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1
24,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,0
25,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0
26,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1
27,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0
28,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0

In [1412]:
predictsss=rf5.predict(copycat)
print(predictsss)

['DC' 'CSK' 'RCB' 'KXIP' 'MI' 'RCB' 'CSK' 'SRH' 'MI' 'KXIP' 'RR' 'KKR'
 'RR' 'RR' 'DC' 'RR' 'RR' 'RR' 'DC' 'DC' 'RCB' 'CSK' 'RR' 'RR' 'RCB' 'RR'
 'CSK' 'RCB' 'RR']

[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  16 out of  20 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=8)]: Done  20 out of  20 | elapsed:    0.0s finished